# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import ai_pb2 as proto_dot_ai__pb2


class AIServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SelfHealLocator = channel.unary_unary(
                '/automation.v1.AIService/SelfHealLocator',
                request_serializer=proto_dot_ai__pb2.SelfHealRequest.SerializeToString,
                response_deserializer=proto_dot_ai__pb2.SelfHealResponse.FromString,
                )
        self.SuggestLocators = channel.unary_unary(
                '/automation.v1.AIService/SuggestLocators',
                request_serializer=proto_dot_ai__pb2.SuggestLocatorsRequest.SerializeToString,
                response_deserializer=proto_dot_ai__pb2.SuggestLocatorsResponse.FromString,
                )
        self.AnalyzeFailure = channel.unary_unary(
                '/automation.v1.AIService/AnalyzeFailure',
                request_serializer=proto_dot_ai__pb2.AnalyzeFailureRequest.SerializeToString,
                response_deserializer=proto_dot_ai__pb2.AnalyzeFailureResponse.FromString,
                )


class AIServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SelfHealLocator(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SuggestLocators(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AnalyzeFailure(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AIServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SelfHealLocator': grpc.unary_unary_rpc_method_handler(
                    servicer.SelfHealLocator,
                    request_deserializer=proto_dot_ai__pb2.SelfHealRequest.FromString,
                    response_serializer=proto_dot_ai__pb2.SelfHealResponse.SerializeToString,
            ),
            'SuggestLocators': grpc.unary_unary_rpc_method_handler(
                    servicer.SuggestLocators,
                    request_deserializer=proto_dot_ai__pb2.SuggestLocatorsRequest.FromString,
                    response_serializer=proto_dot_ai__pb2.SuggestLocatorsResponse.SerializeToString,
            ),
            'AnalyzeFailure': grpc.unary_unary_rpc_method_handler(
                    servicer.AnalyzeFailure,
                    request_deserializer=proto_dot_ai__pb2.AnalyzeFailureRequest.FromString,
                    response_serializer=proto_dot_ai__pb2.AnalyzeFailureResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'automation.v1.AIService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AIService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SelfHealLocator(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/automation.v1.AIService/SelfHealLocator',
            proto_dot_ai__pb2.SelfHealRequest.SerializeToString,
            proto_dot_ai__pb2.SelfHealResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SuggestLocators(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/automation.v1.AIService/SuggestLocators',
            proto_dot_ai__pb2.SuggestLocatorsRequest.SerializeToString,
            proto_dot_ai__pb2.SuggestLocatorsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def AnalyzeFailure(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/automation.v1.AIService/AnalyzeFailure',
            proto_dot_ai__pb2.AnalyzeFailureRequest.SerializeToString,
            proto_dot_ai__pb2.AnalyzeFailureResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
