# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/ai.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from proto import locator_pb2 as proto_dot_locator__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eproto/ai.proto\x12\rautomation.v1\x1a\x13proto/locator.proto\"\x86\x01\n\x0fSelfHealRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x30\n\x10original_locator\x18\x02 \x01(\x0b\x32\x16.automation.v1.Locator\x12\x15\n\rerror_message\x18\x03 \x01(\t\x12\x16\n\x0eview_hierarchy\x18\x04 \x01(\t\"i\n\x10SelfHealResponse\x12.\n\x0ehealed_locator\x18\x01 \x01(\x0b\x32\x16.automation.v1.Locator\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x11\n\treasoning\x18\x03 \x01(\t\"D\n\x16SuggestLocatorsRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x16\n\x0eview_hierarchy\x18\x02 \x01(\t\"\xc1\x01\n\x17SuggestLocatorsResponse\x12\x46\n\x0bsuggestions\x18\x01 \x03(\x0b\x32\x31.automation.v1.SuggestLocatorsResponse.Suggestion\x1a^\n\nSuggestion\x12\'\n\x07locator\x18\x01 \x01(\x0b\x32\x16.automation.v1.Locator\x12\x0e\n\x06reason\x18\x02 \x01(\t\x12\x17\n\x0fstability_score\x18\x03 \x01(\x02\"j\n\x15\x41nalyzeFailureRequest\x12\x15\n\rerror_message\x18\x01 \x01(\t\x12\x13\n\x0bstack_trace\x18\x02 \x01(\t\x12\x17\n\x0fscreenshot_data\x18\x03 \x01(\x0c\x12\x0c\n\x04logs\x18\x04 \x01(\t\"C\n\x16\x41nalyzeFailureResponse\x12\x10\n\x08\x61nalysis\x18\x01 \x01(\t\x12\x17\n\x0frecommended_fix\x18\x02 \x01(\t2\xa0\x02\n\tAIService\x12R\n\x0fSelfHealLocator\x12\x1e.automation.v1.SelfHealRequest\x1a\x1f.automation.v1.SelfHealResponse\x12`\n\x0fSuggestLocators\x12%.automation.v1.SuggestLocatorsRequest\x1a&.automation.v1.SuggestLocatorsResponse\x12]\n\x0e\x41nalyzeFailure\x12$.automation.v1.AnalyzeFailureRequest\x1a%.automation.v1.AnalyzeFailureResponseB*Z(github.com/ranjith035/morego/proto/v1;v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.ai_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z(github.com/ranjith035/morego/proto/v1;v1'
  _globals['_SELFHEALREQUEST']._serialized_start=55
  _globals['_SELFHEALREQUEST']._serialized_end=189
  _globals['_SELFHEALRESPONSE']._serialized_start=191
  _globals['_SELFHEALRESPONSE']._serialized_end=296
  _globals['_SUGGESTLOCATORSREQUEST']._serialized_start=298
  _globals['_SUGGESTLOCATORSREQUEST']._serialized_end=366
  _globals['_SUGGESTLOCATORSRESPONSE']._serialized_start=369
  _globals['_SUGGESTLOCATORSRESPONSE']._serialized_end=562
  _globals['_SUGGESTLOCATORSRESPONSE_SUGGESTION']._serialized_start=468
  _globals['_SUGGESTLOCATORSRESPONSE_SUGGESTION']._serialized_end=562
  _globals['_ANALYZEFAILUREREQUEST']._serialized_start=564
  _globals['_ANALYZEFAILUREREQUEST']._serialized_end=670
  _globals['_ANALYZEFAILURERESPONSE']._serialized_start=672
  _globals['_ANALYZEFAILURERESPONSE']._serialized_end=739
  _globals['_AISERVICE']._serialized_start=742
  _globals['_AISERVICE']._serialized_end=1030
# @@protoc_insertion_point(module_scope)
