# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import device_pb2 as proto_dot_device__pb2


class DeviceServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ListDevices = channel.unary_unary(
                '/automation.v1.DeviceService/ListDevices',
                request_serializer=proto_dot_device__pb2.ListDevicesRequest.SerializeToString,
                response_deserializer=proto_dot_device__pb2.ListDevicesResponse.FromString,
                )
        self.GetDeviceCapabilities = channel.unary_unary(
                '/automation.v1.DeviceService/GetDeviceCapabilities',
                request_serializer=proto_dot_device__pb2.GetDeviceCapabilitiesRequest.SerializeToString,
                response_deserializer=proto_dot_device__pb2.GetDeviceCapabilitiesResponse.FromString,
                )
        self.InstallApp = channel.unary_unary(
                '/automation.v1.DeviceService/InstallApp',
                request_serializer=proto_dot_device__pb2.InstallAppRequest.SerializeToString,
                response_deserializer=proto_dot_device__pb2.InstallAppResponse.FromString,
                )
        self.UninstallApp = channel.unary_unary(
                '/automation.v1.DeviceService/UninstallApp',
                request_serializer=proto_dot_device__pb2.UninstallAppRequest.SerializeToString,
                response_deserializer=proto_dot_device__pb2.UninstallAppResponse.FromString,
                )
        self.LaunchApp = channel.unary_unary(
                '/automation.v1.DeviceService/LaunchApp',
                request_serializer=proto_dot_device__pb2.LaunchAppRequest.SerializeToString,
                response_deserializer=proto_dot_device__pb2.LaunchAppResponse.FromString,
                )
        self.TerminateApp = channel.unary_unary(
                '/automation.v1.DeviceService/TerminateApp',
                request_serializer=proto_dot_device__pb2.TerminateAppRequest.SerializeToString,
                response_deserializer=proto_dot_device__pb2.TerminateAppResponse.FromString,
                )


class DeviceServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ListDevices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDeviceCapabilities(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def InstallApp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UninstallApp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LaunchApp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TerminateApp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DeviceServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ListDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDevices,
                    request_deserializer=proto_dot_device__pb2.ListDevicesRequest.FromString,
                    response_serializer=proto_dot_device__pb2.ListDevicesResponse.SerializeToString,
            ),
            'GetDeviceCapabilities': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDeviceCapabilities,
                    request_deserializer=proto_dot_device__pb2.GetDeviceCapabilitiesRequest.FromString,
                    response_serializer=proto_dot_device__pb2.GetDeviceCapabilitiesResponse.SerializeToString,
            ),
            'InstallApp': grpc.unary_unary_rpc_method_handler(
                    servicer.InstallApp,
                    request_deserializer=proto_dot_device__pb2.InstallAppRequest.FromString,
                    response_serializer=proto_dot_device__pb2.InstallAppResponse.SerializeToString,
            ),
            'UninstallApp': grpc.unary_unary_rpc_method_handler(
                    servicer.UninstallApp,
                    request_deserializer=proto_dot_device__pb2.UninstallAppRequest.FromString,
                    response_serializer=proto_dot_device__pb2.UninstallAppResponse.SerializeToString,
            ),
            'LaunchApp': grpc.unary_unary_rpc_method_handler(
                    servicer.LaunchApp,
                    request_deserializer=proto_dot_device__pb2.LaunchAppRequest.FromString,
                    response_serializer=proto_dot_device__pb2.LaunchAppResponse.SerializeToString,
            ),
            'TerminateApp': grpc.unary_unary_rpc_method_handler(
                    servicer.TerminateApp,
                    request_deserializer=proto_dot_device__pb2.TerminateAppRequest.FromString,
                    response_serializer=proto_dot_device__pb2.TerminateAppResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'automation.v1.DeviceService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DeviceService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ListDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/automation.v1.DeviceService/ListDevices',
            proto_dot_device__pb2.ListDevicesRequest.SerializeToString,
            proto_dot_device__pb2.ListDevicesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDeviceCapabilities(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/automation.v1.DeviceService/GetDeviceCapabilities',
            proto_dot_device__pb2.GetDeviceCapabilitiesRequest.SerializeToString,
            proto_dot_device__pb2.GetDeviceCapabilitiesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def InstallApp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/automation.v1.DeviceService/InstallApp',
            proto_dot_device__pb2.InstallAppRequest.SerializeToString,
            proto_dot_device__pb2.InstallAppResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UninstallApp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/automation.v1.DeviceService/UninstallApp',
            proto_dot_device__pb2.UninstallAppRequest.SerializeToString,
            proto_dot_device__pb2.UninstallAppResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LaunchApp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/automation.v1.DeviceService/LaunchApp',
            proto_dot_device__pb2.LaunchAppRequest.SerializeToString,
            proto_dot_device__pb2.LaunchAppResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def TerminateApp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/automation.v1.DeviceService/TerminateApp',
            proto_dot_device__pb2.TerminateAppRequest.SerializeToString,
            proto_dot_device__pb2.TerminateAppResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
