# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import driver_pb2 as proto_dot_driver__pb2
from proto import locator_pb2 as proto_dot_locator__pb2


class DriverServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConnectDriver = channel.unary_unary(
                '/automation.v1.DriverService/ConnectDriver',
                request_serializer=proto_dot_driver__pb2.ConnectDriverRequest.SerializeToString,
                response_deserializer=proto_dot_driver__pb2.ConnectDriverResponse.FromString,
                )
        self.DisconnectDriver = channel.unary_unary(
                '/automation.v1.DriverService/DisconnectDriver',
                request_serializer=proto_dot_driver__pb2.DisconnectDriverRequest.SerializeToString,
                response_deserializer=proto_dot_driver__pb2.DisconnectDriverResponse.FromString,
                )
        self.FindElement = channel.unary_unary(
                '/automation.v1.DriverService/FindElement',
                request_serializer=proto_dot_locator__pb2.FindElementRequest.SerializeToString,
                response_deserializer=proto_dot_locator__pb2.FindElementResponse.FromString,
                )
        self.FindElements = channel.unary_unary(
                '/automation.v1.DriverService/FindElements',
                request_serializer=proto_dot_locator__pb2.FindElementsRequest.SerializeToString,
                response_deserializer=proto_dot_locator__pb2.FindElementsResponse.FromString,
                )
        self.Click = channel.unary_unary(
                '/automation.v1.DriverService/Click',
                request_serializer=proto_dot_driver__pb2.ClickRequest.SerializeToString,
                response_deserializer=proto_dot_driver__pb2.ClickResponse.FromString,
                )
        self.Fill = channel.unary_unary(
                '/automation.v1.DriverService/Fill',
                request_serializer=proto_dot_driver__pb2.FillRequest.SerializeToString,
                response_deserializer=proto_dot_driver__pb2.FillResponse.FromString,
                )
        self.Swipe = channel.unary_unary(
                '/automation.v1.DriverService/Swipe',
                request_serializer=proto_dot_driver__pb2.SwipeRequest.SerializeToString,
                response_deserializer=proto_dot_driver__pb2.SwipeResponse.FromString,
                )
        self.Screenshot = channel.unary_unary(
                '/automation.v1.DriverService/Screenshot',
                request_serializer=proto_dot_driver__pb2.ScreenshotRequest.SerializeToString,
                response_deserializer=proto_dot_driver__pb2.ScreenshotResponse.FromString,
                )
        self.GetSource = channel.unary_unary(
                '/automation.v1.DriverService/GetSource',
                request_serializer=proto_dot_driver__pb2.GetSourceRequest.SerializeToString,
                response_deserializer=proto_dot_driver__pb2.GetSourceResponse.FromString,
                )
        self.ExecuteScript = channel.unary_unary(
                '/automation.v1.DriverService/ExecuteScript',
                request_serializer=proto_dot_driver__pb2.ExecuteScriptRequest.SerializeToString,
                response_deserializer=proto_dot_driver__pb2.ExecuteScriptResponse.FromString,
                )


class DriverServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ConnectDriver(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DisconnectDriver(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindElement(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def FindElements(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Click(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Fill(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Swipe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Screenshot(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSource(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ExecuteScript(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DriverServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConnectDriver': grpc.unary_unary_rpc_method_handler(
                    servicer.ConnectDriver,
                    request_deserializer=proto_dot_driver__pb2.ConnectDriverRequest.FromString,
                    response_serializer=proto_dot_driver__pb2.ConnectDriverResponse.SerializeToString,
            ),
            'DisconnectDriver': grpc.unary_unary_rpc_method_handler(
                    servicer.DisconnectDriver,
                    request_deserializer=proto_dot_driver__pb2.DisconnectDriverRequest.FromString,
                    response_serializer=proto_dot_driver__pb2.DisconnectDriverResponse.SerializeToString,
            ),
            'FindElement': grpc.unary_unary_rpc_method_handler(
                    servicer.FindElement,
                    request_deserializer=proto_dot_locator__pb2.FindElementRequest.FromString,
                    response_serializer=proto_dot_locator__pb2.FindElementResponse.SerializeToString,
            ),
            'FindElements': grpc.unary_unary_rpc_method_handler(
                    servicer.FindElements,
                    request_deserializer=proto_dot_locator__pb2.FindElementsRequest.FromString,
                    response_serializer=proto_dot_locator__pb2.FindElementsResponse.SerializeToString,
            ),
            'Click': grpc.unary_unary_rpc_method_handler(
                    servicer.Click,
                    request_deserializer=proto_dot_driver__pb2.ClickRequest.FromString,
                    response_serializer=proto_dot_driver__pb2.ClickResponse.SerializeToString,
            ),
            'Fill': grpc.unary_unary_rpc_method_handler(
                    servicer.Fill,
                    request_deserializer=proto_dot_driver__pb2.FillRequest.FromString,
                    response_serializer=proto_dot_driver__pb2.FillResponse.SerializeToString,
            ),
            'Swipe': grpc.unary_unary_rpc_method_handler(
                    servicer.Swipe,
                    request_deserializer=proto_dot_driver__pb2.SwipeRequest.FromString,
                    response_serializer=proto_dot_driver__pb2.SwipeResponse.SerializeToString,
            ),
            'Screenshot': grpc.unary_unary_rpc_method_handler(
                    servicer.Screenshot,
                    request_deserializer=proto_dot_driver__pb2.ScreenshotRequest.FromString,
                    response_serializer=proto_dot_driver__pb2.ScreenshotResponse.SerializeToString,
            ),
            'GetSource': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSource,
                    request_deserializer=proto_dot_driver__pb2.GetSourceRequest.FromString,
                    response_serializer=proto_dot_driver__pb2.GetSourceResponse.SerializeToString,
            ),
            'ExecuteScript': grpc.unary_unary_rpc_method_handler(
                    servicer.ExecuteScript,
                    request_deserializer=proto_dot_driver__pb2.ExecuteScriptRequest.FromString,
                    response_serializer=proto_dot_driver__pb2.ExecuteScriptResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'automation.v1.DriverService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class DriverService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ConnectDriver(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/automation.v1.DriverService/ConnectDriver',
            proto_dot_driver__pb2.ConnectDriverRequest.SerializeToString,
            proto_dot_driver__pb2.ConnectDriverResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DisconnectDriver(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/automation.v1.DriverService/DisconnectDriver',
            proto_dot_driver__pb2.DisconnectDriverRequest.SerializeToString,
            proto_dot_driver__pb2.DisconnectDriverResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FindElement(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/automation.v1.DriverService/FindElement',
            proto_dot_locator__pb2.FindElementRequest.SerializeToString,
            proto_dot_locator__pb2.FindElementResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def FindElements(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/automation.v1.DriverService/FindElements',
            proto_dot_locator__pb2.FindElementsRequest.SerializeToString,
            proto_dot_locator__pb2.FindElementsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Click(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/automation.v1.DriverService/Click',
            proto_dot_driver__pb2.ClickRequest.SerializeToString,
            proto_dot_driver__pb2.ClickResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Fill(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/automation.v1.DriverService/Fill',
            proto_dot_driver__pb2.FillRequest.SerializeToString,
            proto_dot_driver__pb2.FillResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Swipe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/automation.v1.DriverService/Swipe',
            proto_dot_driver__pb2.SwipeRequest.SerializeToString,
            proto_dot_driver__pb2.SwipeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Screenshot(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/automation.v1.DriverService/Screenshot',
            proto_dot_driver__pb2.ScreenshotRequest.SerializeToString,
            proto_dot_driver__pb2.ScreenshotResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSource(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/automation.v1.DriverService/GetSource',
            proto_dot_driver__pb2.GetSourceRequest.SerializeToString,
            proto_dot_driver__pb2.GetSourceResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ExecuteScript(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/automation.v1.DriverService/ExecuteScript',
            proto_dot_driver__pb2.ExecuteScriptRequest.SerializeToString,
            proto_dot_driver__pb2.ExecuteScriptResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
