# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import plugin_pb2 as proto_dot_plugin__pb2


class PluginServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterPlugin = channel.unary_unary(
                '/automation.v1.PluginService/RegisterPlugin',
                request_serializer=proto_dot_plugin__pb2.RegisterPluginRequest.SerializeToString,
                response_deserializer=proto_dot_plugin__pb2.RegisterPluginResponse.FromString,
                )
        self.StreamHooks = channel.unary_stream(
                '/automation.v1.PluginService/StreamHooks',
                request_serializer=proto_dot_plugin__pb2.StreamHooksRequest.SerializeToString,
                response_deserializer=proto_dot_plugin__pb2.HookInvocation.FromString,
                )
        self.SubmitHookResult = channel.unary_unary(
                '/automation.v1.PluginService/SubmitHookResult',
                request_serializer=proto_dot_plugin__pb2.HookResult.SerializeToString,
                response_deserializer=proto_dot_plugin__pb2.HookResultResponse.FromString,
                )


class PluginServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RegisterPlugin(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamHooks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitHookResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PluginServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterPlugin': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterPlugin,
                    request_deserializer=proto_dot_plugin__pb2.RegisterPluginRequest.FromString,
                    response_serializer=proto_dot_plugin__pb2.RegisterPluginResponse.SerializeToString,
            ),
            'StreamHooks': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamHooks,
                    request_deserializer=proto_dot_plugin__pb2.StreamHooksRequest.FromString,
                    response_serializer=proto_dot_plugin__pb2.HookInvocation.SerializeToString,
            ),
            'SubmitHookResult': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitHookResult,
                    request_deserializer=proto_dot_plugin__pb2.HookResult.FromString,
                    response_serializer=proto_dot_plugin__pb2.HookResultResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'automation.v1.PluginService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PluginService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RegisterPlugin(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/automation.v1.PluginService/RegisterPlugin',
            proto_dot_plugin__pb2.RegisterPluginRequest.SerializeToString,
            proto_dot_plugin__pb2.RegisterPluginResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamHooks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/automation.v1.PluginService/StreamHooks',
            proto_dot_plugin__pb2.StreamHooksRequest.SerializeToString,
            proto_dot_plugin__pb2.HookInvocation.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SubmitHookResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/automation.v1.PluginService/SubmitHookResult',
            proto_dot_plugin__pb2.HookResult.SerializeToString,
            proto_dot_plugin__pb2.HookResultResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
