# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/plugin.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12proto/plugin.proto\x12\rautomation.v1\"X\n\x15RegisterPluginRequest\x12\x13\n\x0bplugin_name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x19\n\x11subscribed_events\x18\x03 \x03(\t\"S\n\x16RegisterPluginResponse\x12\x17\n\x0fregistration_id\x18\x01 \x01(\t\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x02 \x01(\x08\x12\x0e\n\x06reason\x18\x03 \x01(\t\"-\n\x12StreamHooksRequest\x12\x17\n\x0fregistration_id\x18\x01 \x01(\t\"\xb6\x01\n\x0eHookInvocation\x12\x0f\n\x07hook_id\x18\x01 \x01(\t\x12\x12\n\nevent_name\x18\x02 \x01(\t\x12\x12\n\nsession_id\x18\x03 \x01(\t\x12;\n\x07payload\x18\x04 \x03(\x0b\x32*.automation.v1.HookInvocation.PayloadEntry\x1a.\n\x0cPayloadEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xd2\x01\n\nHookResult\x12\x0f\n\x07hook_id\x18\x01 \x01(\t\x12\x1a\n\x12\x63ontinue_execution\x18\x02 \x01(\x08\x12\x15\n\rerror_message\x18\x03 \x01(\t\x12H\n\x10modified_payload\x18\x04 \x03(\x0b\x32..automation.v1.HookResult.ModifiedPayloadEntry\x1a\x36\n\x14ModifiedPayloadEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"%\n\x12HookResultResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\x93\x02\n\rPluginService\x12]\n\x0eRegisterPlugin\x12$.automation.v1.RegisterPluginRequest\x1a%.automation.v1.RegisterPluginResponse\x12Q\n\x0bStreamHooks\x12!.automation.v1.StreamHooksRequest\x1a\x1d.automation.v1.HookInvocation0\x01\x12P\n\x10SubmitHookResult\x12\x19.automation.v1.HookResult\x1a!.automation.v1.HookResultResponseB*Z(github.com/ranjith035/morego/proto/v1;v1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.plugin_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z(github.com/ranjith035/morego/proto/v1;v1'
  _globals['_HOOKINVOCATION_PAYLOADENTRY']._options = None
  _globals['_HOOKINVOCATION_PAYLOADENTRY']._serialized_options = b'8\001'
  _globals['_HOOKRESULT_MODIFIEDPAYLOADENTRY']._options = None
  _globals['_HOOKRESULT_MODIFIEDPAYLOADENTRY']._serialized_options = b'8\001'
  _globals['_REGISTERPLUGINREQUEST']._serialized_start=37
  _globals['_REGISTERPLUGINREQUEST']._serialized_end=125
  _globals['_REGISTERPLUGINRESPONSE']._serialized_start=127
  _globals['_REGISTERPLUGINRESPONSE']._serialized_end=210
  _globals['_STREAMHOOKSREQUEST']._serialized_start=212
  _globals['_STREAMHOOKSREQUEST']._serialized_end=257
  _globals['_HOOKINVOCATION']._serialized_start=260
  _globals['_HOOKINVOCATION']._serialized_end=442
  _globals['_HOOKINVOCATION_PAYLOADENTRY']._serialized_start=396
  _globals['_HOOKINVOCATION_PAYLOADENTRY']._serialized_end=442
  _globals['_HOOKRESULT']._serialized_start=445
  _globals['_HOOKRESULT']._serialized_end=655
  _globals['_HOOKRESULT_MODIFIEDPAYLOADENTRY']._serialized_start=601
  _globals['_HOOKRESULT_MODIFIEDPAYLOADENTRY']._serialized_end=655
  _globals['_HOOKRESULTRESPONSE']._serialized_start=657
  _globals['_HOOKRESULTRESPONSE']._serialized_end=694
  _globals['_PLUGINSERVICE']._serialized_start=697
  _globals['_PLUGINSERVICE']._serialized_end=972
# @@protoc_insertion_point(module_scope)
