# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import recorder_pb2 as proto_dot_recorder__pb2


class RecorderServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartRecording = channel.unary_unary(
                '/automation.v1.RecorderService/StartRecording',
                request_serializer=proto_dot_recorder__pb2.StartRecordingRequest.SerializeToString,
                response_deserializer=proto_dot_recorder__pb2.StartRecordingResponse.FromString,
                )
        self.StopRecording = channel.unary_unary(
                '/automation.v1.RecorderService/StopRecording',
                request_serializer=proto_dot_recorder__pb2.StopRecordingRequest.SerializeToString,
                response_deserializer=proto_dot_recorder__pb2.StopRecordingResponse.FromString,
                )
        self.StreamEvents = channel.unary_stream(
                '/automation.v1.RecorderService/StreamEvents',
                request_serializer=proto_dot_recorder__pb2.StreamEventsRequest.SerializeToString,
                response_deserializer=proto_dot_recorder__pb2.RecordedEvent.FromString,
                )


class RecorderServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartRecording(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopRecording(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamEvents(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RecorderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartRecording': grpc.unary_unary_rpc_method_handler(
                    servicer.StartRecording,
                    request_deserializer=proto_dot_recorder__pb2.StartRecordingRequest.FromString,
                    response_serializer=proto_dot_recorder__pb2.StartRecordingResponse.SerializeToString,
            ),
            'StopRecording': grpc.unary_unary_rpc_method_handler(
                    servicer.StopRecording,
                    request_deserializer=proto_dot_recorder__pb2.StopRecordingRequest.FromString,
                    response_serializer=proto_dot_recorder__pb2.StopRecordingResponse.SerializeToString,
            ),
            'StreamEvents': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamEvents,
                    request_deserializer=proto_dot_recorder__pb2.StreamEventsRequest.FromString,
                    response_serializer=proto_dot_recorder__pb2.RecordedEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'automation.v1.RecorderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class RecorderService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartRecording(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/automation.v1.RecorderService/StartRecording',
            proto_dot_recorder__pb2.StartRecordingRequest.SerializeToString,
            proto_dot_recorder__pb2.StartRecordingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StopRecording(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/automation.v1.RecorderService/StopRecording',
            proto_dot_recorder__pb2.StopRecordingRequest.SerializeToString,
            proto_dot_recorder__pb2.StopRecordingResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StreamEvents(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/automation.v1.RecorderService/StreamEvents',
            proto_dot_recorder__pb2.StreamEventsRequest.SerializeToString,
            proto_dot_recorder__pb2.RecordedEvent.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
