# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import reporter_pb2 as proto_dot_reporter__pb2


class ReporterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReportSuiteStart = channel.unary_unary(
                '/automation.v1.ReporterService/ReportSuiteStart',
                request_serializer=proto_dot_reporter__pb2.ReportSuiteStartRequest.SerializeToString,
                response_deserializer=proto_dot_reporter__pb2.ReportSuiteStartResponse.FromString,
                )
        self.ReportTestStart = channel.unary_unary(
                '/automation.v1.ReporterService/ReportTestStart',
                request_serializer=proto_dot_reporter__pb2.ReportTestStartRequest.SerializeToString,
                response_deserializer=proto_dot_reporter__pb2.ReportTestStartResponse.FromString,
                )
        self.ReportTestEnd = channel.unary_unary(
                '/automation.v1.ReporterService/ReportTestEnd',
                request_serializer=proto_dot_reporter__pb2.ReportTestEndRequest.SerializeToString,
                response_deserializer=proto_dot_reporter__pb2.ReportTestEndResponse.FromString,
                )
        self.ReportSuiteEnd = channel.unary_unary(
                '/automation.v1.ReporterService/ReportSuiteEnd',
                request_serializer=proto_dot_reporter__pb2.ReportSuiteEndRequest.SerializeToString,
                response_deserializer=proto_dot_reporter__pb2.ReportSuiteEndResponse.FromString,
                )
        self.UploadTestArtifact = channel.stream_unary(
                '/automation.v1.ReporterService/UploadTestArtifact',
                request_serializer=proto_dot_reporter__pb2.UploadArtifactRequest.SerializeToString,
                response_deserializer=proto_dot_reporter__pb2.UploadArtifactResponse.FromString,
                )


class ReporterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ReportSuiteStart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportTestStart(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportTestEnd(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportSuiteEnd(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadTestArtifact(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ReporterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReportSuiteStart': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportSuiteStart,
                    request_deserializer=proto_dot_reporter__pb2.ReportSuiteStartRequest.FromString,
                    response_serializer=proto_dot_reporter__pb2.ReportSuiteStartResponse.SerializeToString,
            ),
            'ReportTestStart': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportTestStart,
                    request_deserializer=proto_dot_reporter__pb2.ReportTestStartRequest.FromString,
                    response_serializer=proto_dot_reporter__pb2.ReportTestStartResponse.SerializeToString,
            ),
            'ReportTestEnd': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportTestEnd,
                    request_deserializer=proto_dot_reporter__pb2.ReportTestEndRequest.FromString,
                    response_serializer=proto_dot_reporter__pb2.ReportTestEndResponse.SerializeToString,
            ),
            'ReportSuiteEnd': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportSuiteEnd,
                    request_deserializer=proto_dot_reporter__pb2.ReportSuiteEndRequest.FromString,
                    response_serializer=proto_dot_reporter__pb2.ReportSuiteEndResponse.SerializeToString,
            ),
            'UploadTestArtifact': grpc.stream_unary_rpc_method_handler(
                    servicer.UploadTestArtifact,
                    request_deserializer=proto_dot_reporter__pb2.UploadArtifactRequest.FromString,
                    response_serializer=proto_dot_reporter__pb2.UploadArtifactResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'automation.v1.ReporterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ReporterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ReportSuiteStart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/automation.v1.ReporterService/ReportSuiteStart',
            proto_dot_reporter__pb2.ReportSuiteStartRequest.SerializeToString,
            proto_dot_reporter__pb2.ReportSuiteStartResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReportTestStart(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/automation.v1.ReporterService/ReportTestStart',
            proto_dot_reporter__pb2.ReportTestStartRequest.SerializeToString,
            proto_dot_reporter__pb2.ReportTestStartResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReportTestEnd(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/automation.v1.ReporterService/ReportTestEnd',
            proto_dot_reporter__pb2.ReportTestEndRequest.SerializeToString,
            proto_dot_reporter__pb2.ReportTestEndResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ReportSuiteEnd(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/automation.v1.ReporterService/ReportSuiteEnd',
            proto_dot_reporter__pb2.ReportSuiteEndRequest.SerializeToString,
            proto_dot_reporter__pb2.ReportSuiteEndResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UploadTestArtifact(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(request_iterator, target, '/automation.v1.ReporterService/UploadTestArtifact',
            proto_dot_reporter__pb2.UploadArtifactRequest.SerializeToString,
            proto_dot_reporter__pb2.UploadArtifactResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
