# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import session_pb2 as proto_dot_session__pb2


class SessionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSession = channel.unary_unary(
                '/automation.v1.SessionService/CreateSession',
                request_serializer=proto_dot_session__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=proto_dot_session__pb2.CreateSessionResponse.FromString,
                )
        self.CloseSession = channel.unary_unary(
                '/automation.v1.SessionService/CloseSession',
                request_serializer=proto_dot_session__pb2.CloseSessionRequest.SerializeToString,
                response_deserializer=proto_dot_session__pb2.CloseSessionResponse.FromString,
                )
        self.GetSessionInfo = channel.unary_unary(
                '/automation.v1.SessionService/GetSessionInfo',
                request_serializer=proto_dot_session__pb2.GetSessionInfoRequest.SerializeToString,
                response_deserializer=proto_dot_session__pb2.GetSessionInfoResponse.FromString,
                )
        self.KeepAlive = channel.stream_stream(
                '/automation.v1.SessionService/KeepAlive',
                request_serializer=proto_dot_session__pb2.KeepAliveRequest.SerializeToString,
                response_deserializer=proto_dot_session__pb2.KeepAliveResponse.FromString,
                )


class SessionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CloseSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSessionInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def KeepAlive(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SessionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=proto_dot_session__pb2.CreateSessionRequest.FromString,
                    response_serializer=proto_dot_session__pb2.CreateSessionResponse.SerializeToString,
            ),
            'CloseSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CloseSession,
                    request_deserializer=proto_dot_session__pb2.CloseSessionRequest.FromString,
                    response_serializer=proto_dot_session__pb2.CloseSessionResponse.SerializeToString,
            ),
            'GetSessionInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSessionInfo,
                    request_deserializer=proto_dot_session__pb2.GetSessionInfoRequest.FromString,
                    response_serializer=proto_dot_session__pb2.GetSessionInfoResponse.SerializeToString,
            ),
            'KeepAlive': grpc.stream_stream_rpc_method_handler(
                    servicer.KeepAlive,
                    request_deserializer=proto_dot_session__pb2.KeepAliveRequest.FromString,
                    response_serializer=proto_dot_session__pb2.KeepAliveResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'automation.v1.SessionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SessionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/automation.v1.SessionService/CreateSession',
            proto_dot_session__pb2.CreateSessionRequest.SerializeToString,
            proto_dot_session__pb2.CreateSessionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CloseSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/automation.v1.SessionService/CloseSession',
            proto_dot_session__pb2.CloseSessionRequest.SerializeToString,
            proto_dot_session__pb2.CloseSessionResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSessionInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/automation.v1.SessionService/GetSessionInfo',
            proto_dot_session__pb2.GetSessionInfoRequest.SerializeToString,
            proto_dot_session__pb2.GetSessionInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def KeepAlive(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(request_iterator, target, '/automation.v1.SessionService/KeepAlive',
            proto_dot_session__pb2.KeepAliveRequest.SerializeToString,
            proto_dot_session__pb2.KeepAliveResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
