// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.25.3
// source: proto/ai.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SelfHealRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	SessionId       string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	OriginalLocator *Locator               `protobuf:"bytes,2,opt,name=original_locator,json=originalLocator,proto3" json:"original_locator,omitempty"`
	ErrorMessage    string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ViewHierarchy   string                 `protobuf:"bytes,4,opt,name=view_hierarchy,json=viewHierarchy,proto3" json:"view_hierarchy,omitempty"` // Current page layout (XML/JSON representation)
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SelfHealRequest) Reset() {
	*x = SelfHealRequest{}
	mi := &file_proto_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelfHealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelfHealRequest) ProtoMessage() {}

func (x *SelfHealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelfHealRequest.ProtoReflect.Descriptor instead.
func (*SelfHealRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_proto_rawDescGZIP(), []int{0}
}

func (x *SelfHealRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SelfHealRequest) GetOriginalLocator() *Locator {
	if x != nil {
		return x.OriginalLocator
	}
	return nil
}

func (x *SelfHealRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *SelfHealRequest) GetViewHierarchy() string {
	if x != nil {
		return x.ViewHierarchy
	}
	return ""
}

type SelfHealResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HealedLocator *Locator               `protobuf:"bytes,1,opt,name=healed_locator,json=healedLocator,proto3" json:"healed_locator,omitempty"`
	Confidence    float32                `protobuf:"fixed32,2,opt,name=confidence,proto3" json:"confidence,omitempty"` // Value between 0.0 and 1.0
	Reasoning     string                 `protobuf:"bytes,3,opt,name=reasoning,proto3" json:"reasoning,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SelfHealResponse) Reset() {
	*x = SelfHealResponse{}
	mi := &file_proto_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SelfHealResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SelfHealResponse) ProtoMessage() {}

func (x *SelfHealResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SelfHealResponse.ProtoReflect.Descriptor instead.
func (*SelfHealResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_proto_rawDescGZIP(), []int{1}
}

func (x *SelfHealResponse) GetHealedLocator() *Locator {
	if x != nil {
		return x.HealedLocator
	}
	return nil
}

func (x *SelfHealResponse) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *SelfHealResponse) GetReasoning() string {
	if x != nil {
		return x.Reasoning
	}
	return ""
}

type SuggestLocatorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ViewHierarchy string                 `protobuf:"bytes,2,opt,name=view_hierarchy,json=viewHierarchy,proto3" json:"view_hierarchy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestLocatorsRequest) Reset() {
	*x = SuggestLocatorsRequest{}
	mi := &file_proto_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestLocatorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestLocatorsRequest) ProtoMessage() {}

func (x *SuggestLocatorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestLocatorsRequest.ProtoReflect.Descriptor instead.
func (*SuggestLocatorsRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_proto_rawDescGZIP(), []int{2}
}

func (x *SuggestLocatorsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SuggestLocatorsRequest) GetViewHierarchy() string {
	if x != nil {
		return x.ViewHierarchy
	}
	return ""
}

type SuggestLocatorsResponse struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	Suggestions   []*SuggestLocatorsResponse_Suggestion `protobuf:"bytes,1,rep,name=suggestions,proto3" json:"suggestions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SuggestLocatorsResponse) Reset() {
	*x = SuggestLocatorsResponse{}
	mi := &file_proto_ai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestLocatorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestLocatorsResponse) ProtoMessage() {}

func (x *SuggestLocatorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestLocatorsResponse.ProtoReflect.Descriptor instead.
func (*SuggestLocatorsResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_proto_rawDescGZIP(), []int{3}
}

func (x *SuggestLocatorsResponse) GetSuggestions() []*SuggestLocatorsResponse_Suggestion {
	if x != nil {
		return x.Suggestions
	}
	return nil
}

type AnalyzeFailureRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ErrorMessage   string                 `protobuf:"bytes,1,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	StackTrace     string                 `protobuf:"bytes,2,opt,name=stack_trace,json=stackTrace,proto3" json:"stack_trace,omitempty"`
	ScreenshotData []byte                 `protobuf:"bytes,3,opt,name=screenshot_data,json=screenshotData,proto3" json:"screenshot_data,omitempty"` // optional visual context
	Logs           string                 `protobuf:"bytes,4,opt,name=logs,proto3" json:"logs,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AnalyzeFailureRequest) Reset() {
	*x = AnalyzeFailureRequest{}
	mi := &file_proto_ai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeFailureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeFailureRequest) ProtoMessage() {}

func (x *AnalyzeFailureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeFailureRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeFailureRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_proto_rawDescGZIP(), []int{4}
}

func (x *AnalyzeFailureRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *AnalyzeFailureRequest) GetStackTrace() string {
	if x != nil {
		return x.StackTrace
	}
	return ""
}

func (x *AnalyzeFailureRequest) GetScreenshotData() []byte {
	if x != nil {
		return x.ScreenshotData
	}
	return nil
}

func (x *AnalyzeFailureRequest) GetLogs() string {
	if x != nil {
		return x.Logs
	}
	return ""
}

type AnalyzeFailureResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Analysis       string                 `protobuf:"bytes,1,opt,name=analysis,proto3" json:"analysis,omitempty"` // Human readable description of failure causes
	RecommendedFix string                 `protobuf:"bytes,2,opt,name=recommended_fix,json=recommendedFix,proto3" json:"recommended_fix,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AnalyzeFailureResponse) Reset() {
	*x = AnalyzeFailureResponse{}
	mi := &file_proto_ai_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeFailureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeFailureResponse) ProtoMessage() {}

func (x *AnalyzeFailureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeFailureResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeFailureResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_proto_rawDescGZIP(), []int{5}
}

func (x *AnalyzeFailureResponse) GetAnalysis() string {
	if x != nil {
		return x.Analysis
	}
	return ""
}

func (x *AnalyzeFailureResponse) GetRecommendedFix() string {
	if x != nil {
		return x.RecommendedFix
	}
	return ""
}

type SuggestLocatorsResponse_Suggestion struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Locator        *Locator               `protobuf:"bytes,1,opt,name=locator,proto3" json:"locator,omitempty"`
	Reason         string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	StabilityScore float32                `protobuf:"fixed32,3,opt,name=stability_score,json=stabilityScore,proto3" json:"stability_score,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SuggestLocatorsResponse_Suggestion) Reset() {
	*x = SuggestLocatorsResponse_Suggestion{}
	mi := &file_proto_ai_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SuggestLocatorsResponse_Suggestion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuggestLocatorsResponse_Suggestion) ProtoMessage() {}

func (x *SuggestLocatorsResponse_Suggestion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuggestLocatorsResponse_Suggestion.ProtoReflect.Descriptor instead.
func (*SuggestLocatorsResponse_Suggestion) Descriptor() ([]byte, []int) {
	return file_proto_ai_proto_rawDescGZIP(), []int{3, 0}
}

func (x *SuggestLocatorsResponse_Suggestion) GetLocator() *Locator {
	if x != nil {
		return x.Locator
	}
	return nil
}

func (x *SuggestLocatorsResponse_Suggestion) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *SuggestLocatorsResponse_Suggestion) GetStabilityScore() float32 {
	if x != nil {
		return x.StabilityScore
	}
	return 0
}

var File_proto_ai_proto protoreflect.FileDescriptor

const file_proto_ai_proto_rawDesc = "" +
	"\n" +
	"\x0eproto/ai.proto\x12\rautomation.v1\x1a\x13proto/locator.proto\"\xbf\x01\n" +
	"\x0fSelfHealRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12A\n" +
	"\x10original_locator\x18\x02 \x01(\v2\x16.automation.v1.LocatorR\x0foriginalLocator\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12%\n" +
	"\x0eview_hierarchy\x18\x04 \x01(\tR\rviewHierarchy\"\x8f\x01\n" +
	"\x10SelfHealResponse\x12=\n" +
	"\x0ehealed_locator\x18\x01 \x01(\v2\x16.automation.v1.LocatorR\rhealedLocator\x12\x1e\n" +
	"\n" +
	"confidence\x18\x02 \x01(\x02R\n" +
	"confidence\x12\x1c\n" +
	"\treasoning\x18\x03 \x01(\tR\treasoning\"^\n" +
	"\x16SuggestLocatorsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12%\n" +
	"\x0eview_hierarchy\x18\x02 \x01(\tR\rviewHierarchy\"\xef\x01\n" +
	"\x17SuggestLocatorsResponse\x12S\n" +
	"\vsuggestions\x18\x01 \x03(\v21.automation.v1.SuggestLocatorsResponse.SuggestionR\vsuggestions\x1a\x7f\n" +
	"\n" +
	"Suggestion\x120\n" +
	"\alocator\x18\x01 \x01(\v2\x16.automation.v1.LocatorR\alocator\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12'\n" +
	"\x0fstability_score\x18\x03 \x01(\x02R\x0estabilityScore\"\x9a\x01\n" +
	"\x15AnalyzeFailureRequest\x12#\n" +
	"\rerror_message\x18\x01 \x01(\tR\ferrorMessage\x12\x1f\n" +
	"\vstack_trace\x18\x02 \x01(\tR\n" +
	"stackTrace\x12'\n" +
	"\x0fscreenshot_data\x18\x03 \x01(\fR\x0escreenshotData\x12\x12\n" +
	"\x04logs\x18\x04 \x01(\tR\x04logs\"]\n" +
	"\x16AnalyzeFailureResponse\x12\x1a\n" +
	"\banalysis\x18\x01 \x01(\tR\banalysis\x12'\n" +
	"\x0frecommended_fix\x18\x02 \x01(\tR\x0erecommendedFix2\xa0\x02\n" +
	"\tAIService\x12R\n" +
	"\x0fSelfHealLocator\x12\x1e.automation.v1.SelfHealRequest\x1a\x1f.automation.v1.SelfHealResponse\x12`\n" +
	"\x0fSuggestLocators\x12%.automation.v1.SuggestLocatorsRequest\x1a&.automation.v1.SuggestLocatorsResponse\x12]\n" +
	"\x0eAnalyzeFailure\x12$.automation.v1.AnalyzeFailureRequest\x1a%.automation.v1.AnalyzeFailureResponseB*Z(github.com/ranjith035/morego/proto/v1;v1b\x06proto3"

var (
	file_proto_ai_proto_rawDescOnce sync.Once
	file_proto_ai_proto_rawDescData []byte
)

func file_proto_ai_proto_rawDescGZIP() []byte {
	file_proto_ai_proto_rawDescOnce.Do(func() {
		file_proto_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ai_proto_rawDesc), len(file_proto_ai_proto_rawDesc)))
	})
	return file_proto_ai_proto_rawDescData
}

var file_proto_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_ai_proto_goTypes = []any{
	(*SelfHealRequest)(nil),                    // 0: automation.v1.SelfHealRequest
	(*SelfHealResponse)(nil),                   // 1: automation.v1.SelfHealResponse
	(*SuggestLocatorsRequest)(nil),             // 2: automation.v1.SuggestLocatorsRequest
	(*SuggestLocatorsResponse)(nil),            // 3: automation.v1.SuggestLocatorsResponse
	(*AnalyzeFailureRequest)(nil),              // 4: automation.v1.AnalyzeFailureRequest
	(*AnalyzeFailureResponse)(nil),             // 5: automation.v1.AnalyzeFailureResponse
	(*SuggestLocatorsResponse_Suggestion)(nil), // 6: automation.v1.SuggestLocatorsResponse.Suggestion
	(*Locator)(nil),                            // 7: automation.v1.Locator
}
var file_proto_ai_proto_depIdxs = []int32{
	7, // 0: automation.v1.SelfHealRequest.original_locator:type_name -> automation.v1.Locator
	7, // 1: automation.v1.SelfHealResponse.healed_locator:type_name -> automation.v1.Locator
	6, // 2: automation.v1.SuggestLocatorsResponse.suggestions:type_name -> automation.v1.SuggestLocatorsResponse.Suggestion
	7, // 3: automation.v1.SuggestLocatorsResponse.Suggestion.locator:type_name -> automation.v1.Locator
	0, // 4: automation.v1.AIService.SelfHealLocator:input_type -> automation.v1.SelfHealRequest
	2, // 5: automation.v1.AIService.SuggestLocators:input_type -> automation.v1.SuggestLocatorsRequest
	4, // 6: automation.v1.AIService.AnalyzeFailure:input_type -> automation.v1.AnalyzeFailureRequest
	1, // 7: automation.v1.AIService.SelfHealLocator:output_type -> automation.v1.SelfHealResponse
	3, // 8: automation.v1.AIService.SuggestLocators:output_type -> automation.v1.SuggestLocatorsResponse
	5, // 9: automation.v1.AIService.AnalyzeFailure:output_type -> automation.v1.AnalyzeFailureResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_proto_ai_proto_init() }
func file_proto_ai_proto_init() {
	if File_proto_ai_proto != nil {
		return
	}
	file_proto_locator_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ai_proto_rawDesc), len(file_proto_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ai_proto_goTypes,
		DependencyIndexes: file_proto_ai_proto_depIdxs,
		MessageInfos:      file_proto_ai_proto_msgTypes,
	}.Build()
	File_proto_ai_proto = out.File
	file_proto_ai_proto_goTypes = nil
	file_proto_ai_proto_depIdxs = nil
}
