// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: proto/ai.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AIService_SelfHealLocator_FullMethodName = "/automation.v1.AIService/SelfHealLocator"
	AIService_SuggestLocators_FullMethodName = "/automation.v1.AIService/SuggestLocators"
	AIService_AnalyzeFailure_FullMethodName  = "/automation.v1.AIService/AnalyzeFailure"
)

// AIServiceClient is the client API for AIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AIServiceClient interface {
	SelfHealLocator(ctx context.Context, in *SelfHealRequest, opts ...grpc.CallOption) (*SelfHealResponse, error)
	SuggestLocators(ctx context.Context, in *SuggestLocatorsRequest, opts ...grpc.CallOption) (*SuggestLocatorsResponse, error)
	AnalyzeFailure(ctx context.Context, in *AnalyzeFailureRequest, opts ...grpc.CallOption) (*AnalyzeFailureResponse, error)
}

type aIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIServiceClient(cc grpc.ClientConnInterface) AIServiceClient {
	return &aIServiceClient{cc}
}

func (c *aIServiceClient) SelfHealLocator(ctx context.Context, in *SelfHealRequest, opts ...grpc.CallOption) (*SelfHealResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SelfHealResponse)
	err := c.cc.Invoke(ctx, AIService_SelfHealLocator_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) SuggestLocators(ctx context.Context, in *SuggestLocatorsRequest, opts ...grpc.CallOption) (*SuggestLocatorsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SuggestLocatorsResponse)
	err := c.cc.Invoke(ctx, AIService_SuggestLocators_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) AnalyzeFailure(ctx context.Context, in *AnalyzeFailureRequest, opts ...grpc.CallOption) (*AnalyzeFailureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeFailureResponse)
	err := c.cc.Invoke(ctx, AIService_AnalyzeFailure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIServiceServer is the server API for AIService service.
// All implementations must embed UnimplementedAIServiceServer
// for forward compatibility.
type AIServiceServer interface {
	SelfHealLocator(context.Context, *SelfHealRequest) (*SelfHealResponse, error)
	SuggestLocators(context.Context, *SuggestLocatorsRequest) (*SuggestLocatorsResponse, error)
	AnalyzeFailure(context.Context, *AnalyzeFailureRequest) (*AnalyzeFailureResponse, error)
	mustEmbedUnimplementedAIServiceServer()
}

// UnimplementedAIServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIServiceServer struct{}

func (UnimplementedAIServiceServer) SelfHealLocator(context.Context, *SelfHealRequest) (*SelfHealResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SelfHealLocator not implemented")
}
func (UnimplementedAIServiceServer) SuggestLocators(context.Context, *SuggestLocatorsRequest) (*SuggestLocatorsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SuggestLocators not implemented")
}
func (UnimplementedAIServiceServer) AnalyzeFailure(context.Context, *AnalyzeFailureRequest) (*AnalyzeFailureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeFailure not implemented")
}
func (UnimplementedAIServiceServer) mustEmbedUnimplementedAIServiceServer() {}
func (UnimplementedAIServiceServer) testEmbeddedByValue()                   {}

// UnsafeAIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIServiceServer will
// result in compilation errors.
type UnsafeAIServiceServer interface {
	mustEmbedUnimplementedAIServiceServer()
}

func RegisterAIServiceServer(s grpc.ServiceRegistrar, srv AIServiceServer) {
	// If the following call panics, it indicates UnimplementedAIServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIService_ServiceDesc, srv)
}

func _AIService_SelfHealLocator_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SelfHealRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).SelfHealLocator(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_SelfHealLocator_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).SelfHealLocator(ctx, req.(*SelfHealRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_SuggestLocators_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SuggestLocatorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).SuggestLocators(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_SuggestLocators_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).SuggestLocators(ctx, req.(*SuggestLocatorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_AnalyzeFailure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeFailureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).AnalyzeFailure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_AnalyzeFailure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).AnalyzeFailure(ctx, req.(*AnalyzeFailureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AIService_ServiceDesc is the grpc.ServiceDesc for AIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "automation.v1.AIService",
	HandlerType: (*AIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SelfHealLocator",
			Handler:    _AIService_SelfHealLocator_Handler,
		},
		{
			MethodName: "SuggestLocators",
			Handler:    _AIService_SuggestLocators_Handler,
		},
		{
			MethodName: "AnalyzeFailure",
			Handler:    _AIService_AnalyzeFailure_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ai.proto",
}
