// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.25.3
// source: proto/device.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Platform int32

const (
	Platform_PLATFORM_UNSPECIFIED Platform = 0
	Platform_PLATFORM_ANDROID     Platform = 1
	Platform_PLATFORM_IOS         Platform = 2
)

// Enum value maps for Platform.
var (
	Platform_name = map[int32]string{
		0: "PLATFORM_UNSPECIFIED",
		1: "PLATFORM_ANDROID",
		2: "PLATFORM_IOS",
	}
	Platform_value = map[string]int32{
		"PLATFORM_UNSPECIFIED": 0,
		"PLATFORM_ANDROID":     1,
		"PLATFORM_IOS":         2,
	}
)

func (x Platform) Enum() *Platform {
	p := new(Platform)
	*p = x
	return p
}

func (x Platform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Platform) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_device_proto_enumTypes[0].Descriptor()
}

func (Platform) Type() protoreflect.EnumType {
	return &file_proto_device_proto_enumTypes[0]
}

func (x Platform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Platform.Descriptor instead.
func (Platform) EnumDescriptor() ([]byte, []int) {
	return file_proto_device_proto_rawDescGZIP(), []int{0}
}

type DeviceInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Platform      Platform               `protobuf:"varint,3,opt,name=platform,proto3,enum=automation.v1.Platform" json:"platform,omitempty"`
	OsVersion     string                 `protobuf:"bytes,4,opt,name=os_version,json=osVersion,proto3" json:"os_version,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	IsEmulator    bool                   `protobuf:"varint,6,opt,name=is_emulator,json=isEmulator,proto3" json:"is_emulator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceInfo) Reset() {
	*x = DeviceInfo{}
	mi := &file_proto_device_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceInfo) ProtoMessage() {}

func (x *DeviceInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceInfo.ProtoReflect.Descriptor instead.
func (*DeviceInfo) Descriptor() ([]byte, []int) {
	return file_proto_device_proto_rawDescGZIP(), []int{0}
}

func (x *DeviceInfo) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *DeviceInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeviceInfo) GetPlatform() Platform {
	if x != nil {
		return x.Platform
	}
	return Platform_PLATFORM_UNSPECIFIED
}

func (x *DeviceInfo) GetOsVersion() string {
	if x != nil {
		return x.OsVersion
	}
	return ""
}

func (x *DeviceInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *DeviceInfo) GetIsEmulator() bool {
	if x != nil {
		return x.IsEmulator
	}
	return false
}

type ListDevicesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	PlatformFilter Platform               `protobuf:"varint,1,opt,name=platform_filter,json=platformFilter,proto3,enum=automation.v1.Platform" json:"platform_filter,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListDevicesRequest) Reset() {
	*x = ListDevicesRequest{}
	mi := &file_proto_device_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesRequest) ProtoMessage() {}

func (x *ListDevicesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesRequest.ProtoReflect.Descriptor instead.
func (*ListDevicesRequest) Descriptor() ([]byte, []int) {
	return file_proto_device_proto_rawDescGZIP(), []int{1}
}

func (x *ListDevicesRequest) GetPlatformFilter() Platform {
	if x != nil {
		return x.PlatformFilter
	}
	return Platform_PLATFORM_UNSPECIFIED
}

type ListDevicesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Devices       []*DeviceInfo          `protobuf:"bytes,1,rep,name=devices,proto3" json:"devices,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDevicesResponse) Reset() {
	*x = ListDevicesResponse{}
	mi := &file_proto_device_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDevicesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDevicesResponse) ProtoMessage() {}

func (x *ListDevicesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDevicesResponse.ProtoReflect.Descriptor instead.
func (*ListDevicesResponse) Descriptor() ([]byte, []int) {
	return file_proto_device_proto_rawDescGZIP(), []int{2}
}

func (x *ListDevicesResponse) GetDevices() []*DeviceInfo {
	if x != nil {
		return x.Devices
	}
	return nil
}

type GetDeviceCapabilitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceCapabilitiesRequest) Reset() {
	*x = GetDeviceCapabilitiesRequest{}
	mi := &file_proto_device_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceCapabilitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceCapabilitiesRequest) ProtoMessage() {}

func (x *GetDeviceCapabilitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceCapabilitiesRequest.ProtoReflect.Descriptor instead.
func (*GetDeviceCapabilitiesRequest) Descriptor() ([]byte, []int) {
	return file_proto_device_proto_rawDescGZIP(), []int{3}
}

func (x *GetDeviceCapabilitiesRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

type GetDeviceCapabilitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Capabilities  map[string]string      `protobuf:"bytes,2,rep,name=capabilities,proto3" json:"capabilities,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ScreenWidth   int32                  `protobuf:"varint,3,opt,name=screen_width,json=screenWidth,proto3" json:"screen_width,omitempty"`
	ScreenHeight  int32                  `protobuf:"varint,4,opt,name=screen_height,json=screenHeight,proto3" json:"screen_height,omitempty"`
	Density       float32                `protobuf:"fixed32,5,opt,name=density,proto3" json:"density,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDeviceCapabilitiesResponse) Reset() {
	*x = GetDeviceCapabilitiesResponse{}
	mi := &file_proto_device_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDeviceCapabilitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDeviceCapabilitiesResponse) ProtoMessage() {}

func (x *GetDeviceCapabilitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDeviceCapabilitiesResponse.ProtoReflect.Descriptor instead.
func (*GetDeviceCapabilitiesResponse) Descriptor() ([]byte, []int) {
	return file_proto_device_proto_rawDescGZIP(), []int{4}
}

func (x *GetDeviceCapabilitiesResponse) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *GetDeviceCapabilitiesResponse) GetCapabilities() map[string]string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *GetDeviceCapabilitiesResponse) GetScreenWidth() int32 {
	if x != nil {
		return x.ScreenWidth
	}
	return 0
}

func (x *GetDeviceCapabilitiesResponse) GetScreenHeight() int32 {
	if x != nil {
		return x.ScreenHeight
	}
	return 0
}

func (x *GetDeviceCapabilitiesResponse) GetDensity() float32 {
	if x != nil {
		return x.Density
	}
	return 0
}

type InstallAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	AppPath       string                 `protobuf:"bytes,2,opt,name=app_path,json=appPath,proto3" json:"app_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallAppRequest) Reset() {
	*x = InstallAppRequest{}
	mi := &file_proto_device_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallAppRequest) ProtoMessage() {}

func (x *InstallAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallAppRequest.ProtoReflect.Descriptor instead.
func (*InstallAppRequest) Descriptor() ([]byte, []int) {
	return file_proto_device_proto_rawDescGZIP(), []int{5}
}

func (x *InstallAppRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *InstallAppRequest) GetAppPath() string {
	if x != nil {
		return x.AppPath
	}
	return ""
}

type InstallAppResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallAppResponse) Reset() {
	*x = InstallAppResponse{}
	mi := &file_proto_device_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallAppResponse) ProtoMessage() {}

func (x *InstallAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallAppResponse.ProtoReflect.Descriptor instead.
func (*InstallAppResponse) Descriptor() ([]byte, []int) {
	return file_proto_device_proto_rawDescGZIP(), []int{6}
}

func (x *InstallAppResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InstallAppResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type UninstallAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	AppId         string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UninstallAppRequest) Reset() {
	*x = UninstallAppRequest{}
	mi := &file_proto_device_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UninstallAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UninstallAppRequest) ProtoMessage() {}

func (x *UninstallAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UninstallAppRequest.ProtoReflect.Descriptor instead.
func (*UninstallAppRequest) Descriptor() ([]byte, []int) {
	return file_proto_device_proto_rawDescGZIP(), []int{7}
}

func (x *UninstallAppRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *UninstallAppRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type UninstallAppResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UninstallAppResponse) Reset() {
	*x = UninstallAppResponse{}
	mi := &file_proto_device_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UninstallAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UninstallAppResponse) ProtoMessage() {}

func (x *UninstallAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UninstallAppResponse.ProtoReflect.Descriptor instead.
func (*UninstallAppResponse) Descriptor() ([]byte, []int) {
	return file_proto_device_proto_rawDescGZIP(), []int{8}
}

func (x *UninstallAppResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UninstallAppResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type LaunchAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	AppId         string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Arguments     []string               `protobuf:"bytes,3,rep,name=arguments,proto3" json:"arguments,omitempty"`
	Environment   map[string]string      `protobuf:"bytes,4,rep,name=environment,proto3" json:"environment,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaunchAppRequest) Reset() {
	*x = LaunchAppRequest{}
	mi := &file_proto_device_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaunchAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchAppRequest) ProtoMessage() {}

func (x *LaunchAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchAppRequest.ProtoReflect.Descriptor instead.
func (*LaunchAppRequest) Descriptor() ([]byte, []int) {
	return file_proto_device_proto_rawDescGZIP(), []int{9}
}

func (x *LaunchAppRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *LaunchAppRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *LaunchAppRequest) GetArguments() []string {
	if x != nil {
		return x.Arguments
	}
	return nil
}

func (x *LaunchAppRequest) GetEnvironment() map[string]string {
	if x != nil {
		return x.Environment
	}
	return nil
}

type LaunchAppResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Pid           int32                  `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LaunchAppResponse) Reset() {
	*x = LaunchAppResponse{}
	mi := &file_proto_device_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LaunchAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LaunchAppResponse) ProtoMessage() {}

func (x *LaunchAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LaunchAppResponse.ProtoReflect.Descriptor instead.
func (*LaunchAppResponse) Descriptor() ([]byte, []int) {
	return file_proto_device_proto_rawDescGZIP(), []int{10}
}

func (x *LaunchAppResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *LaunchAppResponse) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *LaunchAppResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type TerminateAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeviceId      string                 `protobuf:"bytes,1,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	AppId         string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateAppRequest) Reset() {
	*x = TerminateAppRequest{}
	mi := &file_proto_device_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateAppRequest) ProtoMessage() {}

func (x *TerminateAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateAppRequest.ProtoReflect.Descriptor instead.
func (*TerminateAppRequest) Descriptor() ([]byte, []int) {
	return file_proto_device_proto_rawDescGZIP(), []int{11}
}

func (x *TerminateAppRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *TerminateAppRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type TerminateAppResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateAppResponse) Reset() {
	*x = TerminateAppResponse{}
	mi := &file_proto_device_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateAppResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateAppResponse) ProtoMessage() {}

func (x *TerminateAppResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_device_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateAppResponse.ProtoReflect.Descriptor instead.
func (*TerminateAppResponse) Descriptor() ([]byte, []int) {
	return file_proto_device_proto_rawDescGZIP(), []int{12}
}

func (x *TerminateAppResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TerminateAppResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_proto_device_proto protoreflect.FileDescriptor

const file_proto_device_proto_rawDesc = "" +
	"\n" +
	"\x12proto/device.proto\x12\rautomation.v1\"\xca\x01\n" +
	"\n" +
	"DeviceInfo\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x123\n" +
	"\bplatform\x18\x03 \x01(\x0e2\x17.automation.v1.PlatformR\bplatform\x12\x1d\n" +
	"\n" +
	"os_version\x18\x04 \x01(\tR\tosVersion\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1f\n" +
	"\vis_emulator\x18\x06 \x01(\bR\n" +
	"isEmulator\"V\n" +
	"\x12ListDevicesRequest\x12@\n" +
	"\x0fplatform_filter\x18\x01 \x01(\x0e2\x17.automation.v1.PlatformR\x0eplatformFilter\"J\n" +
	"\x13ListDevicesResponse\x123\n" +
	"\adevices\x18\x01 \x03(\v2\x19.automation.v1.DeviceInfoR\adevices\";\n" +
	"\x1cGetDeviceCapabilitiesRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\"\xc3\x02\n" +
	"\x1dGetDeviceCapabilitiesResponse\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12b\n" +
	"\fcapabilities\x18\x02 \x03(\v2>.automation.v1.GetDeviceCapabilitiesResponse.CapabilitiesEntryR\fcapabilities\x12!\n" +
	"\fscreen_width\x18\x03 \x01(\x05R\vscreenWidth\x12#\n" +
	"\rscreen_height\x18\x04 \x01(\x05R\fscreenHeight\x12\x18\n" +
	"\adensity\x18\x05 \x01(\x02R\adensity\x1a?\n" +
	"\x11CapabilitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"K\n" +
	"\x11InstallAppRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x19\n" +
	"\bapp_path\x18\x02 \x01(\tR\aappPath\"S\n" +
	"\x12InstallAppResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"I\n" +
	"\x13UninstallAppRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\"U\n" +
	"\x14UninstallAppResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\xf8\x01\n" +
	"\x10LaunchAppRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12\x1c\n" +
	"\targuments\x18\x03 \x03(\tR\targuments\x12R\n" +
	"\venvironment\x18\x04 \x03(\v20.automation.v1.LaunchAppRequest.EnvironmentEntryR\venvironment\x1a>\n" +
	"\x10EnvironmentEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"d\n" +
	"\x11LaunchAppResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x10\n" +
	"\x03pid\x18\x02 \x01(\x05R\x03pid\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"I\n" +
	"\x13TerminateAppRequest\x12\x1b\n" +
	"\tdevice_id\x18\x01 \x01(\tR\bdeviceId\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\"U\n" +
	"\x14TerminateAppResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage*L\n" +
	"\bPlatform\x12\x18\n" +
	"\x14PLATFORM_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10PLATFORM_ANDROID\x10\x01\x12\x10\n" +
	"\fPLATFORM_IOS\x10\x022\xae\x04\n" +
	"\rDeviceService\x12T\n" +
	"\vListDevices\x12!.automation.v1.ListDevicesRequest\x1a\".automation.v1.ListDevicesResponse\x12r\n" +
	"\x15GetDeviceCapabilities\x12+.automation.v1.GetDeviceCapabilitiesRequest\x1a,.automation.v1.GetDeviceCapabilitiesResponse\x12Q\n" +
	"\n" +
	"InstallApp\x12 .automation.v1.InstallAppRequest\x1a!.automation.v1.InstallAppResponse\x12W\n" +
	"\fUninstallApp\x12\".automation.v1.UninstallAppRequest\x1a#.automation.v1.UninstallAppResponse\x12N\n" +
	"\tLaunchApp\x12\x1f.automation.v1.LaunchAppRequest\x1a .automation.v1.LaunchAppResponse\x12W\n" +
	"\fTerminateApp\x12\".automation.v1.TerminateAppRequest\x1a#.automation.v1.TerminateAppResponseB*Z(github.com/ranjith035/morego/proto/v1;v1b\x06proto3"

var (
	file_proto_device_proto_rawDescOnce sync.Once
	file_proto_device_proto_rawDescData []byte
)

func file_proto_device_proto_rawDescGZIP() []byte {
	file_proto_device_proto_rawDescOnce.Do(func() {
		file_proto_device_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_device_proto_rawDesc), len(file_proto_device_proto_rawDesc)))
	})
	return file_proto_device_proto_rawDescData
}

var file_proto_device_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_device_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_device_proto_goTypes = []any{
	(Platform)(0),                         // 0: automation.v1.Platform
	(*DeviceInfo)(nil),                    // 1: automation.v1.DeviceInfo
	(*ListDevicesRequest)(nil),            // 2: automation.v1.ListDevicesRequest
	(*ListDevicesResponse)(nil),           // 3: automation.v1.ListDevicesResponse
	(*GetDeviceCapabilitiesRequest)(nil),  // 4: automation.v1.GetDeviceCapabilitiesRequest
	(*GetDeviceCapabilitiesResponse)(nil), // 5: automation.v1.GetDeviceCapabilitiesResponse
	(*InstallAppRequest)(nil),             // 6: automation.v1.InstallAppRequest
	(*InstallAppResponse)(nil),            // 7: automation.v1.InstallAppResponse
	(*UninstallAppRequest)(nil),           // 8: automation.v1.UninstallAppRequest
	(*UninstallAppResponse)(nil),          // 9: automation.v1.UninstallAppResponse
	(*LaunchAppRequest)(nil),              // 10: automation.v1.LaunchAppRequest
	(*LaunchAppResponse)(nil),             // 11: automation.v1.LaunchAppResponse
	(*TerminateAppRequest)(nil),           // 12: automation.v1.TerminateAppRequest
	(*TerminateAppResponse)(nil),          // 13: automation.v1.TerminateAppResponse
	nil,                                   // 14: automation.v1.GetDeviceCapabilitiesResponse.CapabilitiesEntry
	nil,                                   // 15: automation.v1.LaunchAppRequest.EnvironmentEntry
}
var file_proto_device_proto_depIdxs = []int32{
	0,  // 0: automation.v1.DeviceInfo.platform:type_name -> automation.v1.Platform
	0,  // 1: automation.v1.ListDevicesRequest.platform_filter:type_name -> automation.v1.Platform
	1,  // 2: automation.v1.ListDevicesResponse.devices:type_name -> automation.v1.DeviceInfo
	14, // 3: automation.v1.GetDeviceCapabilitiesResponse.capabilities:type_name -> automation.v1.GetDeviceCapabilitiesResponse.CapabilitiesEntry
	15, // 4: automation.v1.LaunchAppRequest.environment:type_name -> automation.v1.LaunchAppRequest.EnvironmentEntry
	2,  // 5: automation.v1.DeviceService.ListDevices:input_type -> automation.v1.ListDevicesRequest
	4,  // 6: automation.v1.DeviceService.GetDeviceCapabilities:input_type -> automation.v1.GetDeviceCapabilitiesRequest
	6,  // 7: automation.v1.DeviceService.InstallApp:input_type -> automation.v1.InstallAppRequest
	8,  // 8: automation.v1.DeviceService.UninstallApp:input_type -> automation.v1.UninstallAppRequest
	10, // 9: automation.v1.DeviceService.LaunchApp:input_type -> automation.v1.LaunchAppRequest
	12, // 10: automation.v1.DeviceService.TerminateApp:input_type -> automation.v1.TerminateAppRequest
	3,  // 11: automation.v1.DeviceService.ListDevices:output_type -> automation.v1.ListDevicesResponse
	5,  // 12: automation.v1.DeviceService.GetDeviceCapabilities:output_type -> automation.v1.GetDeviceCapabilitiesResponse
	7,  // 13: automation.v1.DeviceService.InstallApp:output_type -> automation.v1.InstallAppResponse
	9,  // 14: automation.v1.DeviceService.UninstallApp:output_type -> automation.v1.UninstallAppResponse
	11, // 15: automation.v1.DeviceService.LaunchApp:output_type -> automation.v1.LaunchAppResponse
	13, // 16: automation.v1.DeviceService.TerminateApp:output_type -> automation.v1.TerminateAppResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_proto_device_proto_init() }
func file_proto_device_proto_init() {
	if File_proto_device_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_device_proto_rawDesc), len(file_proto_device_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_device_proto_goTypes,
		DependencyIndexes: file_proto_device_proto_depIdxs,
		EnumInfos:         file_proto_device_proto_enumTypes,
		MessageInfos:      file_proto_device_proto_msgTypes,
	}.Build()
	File_proto_device_proto = out.File
	file_proto_device_proto_goTypes = nil
	file_proto_device_proto_depIdxs = nil
}
