// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: proto/driver.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DriverService_ConnectDriver_FullMethodName    = "/automation.v1.DriverService/ConnectDriver"
	DriverService_DisconnectDriver_FullMethodName = "/automation.v1.DriverService/DisconnectDriver"
	DriverService_FindElement_FullMethodName      = "/automation.v1.DriverService/FindElement"
	DriverService_FindElements_FullMethodName     = "/automation.v1.DriverService/FindElements"
	DriverService_Click_FullMethodName            = "/automation.v1.DriverService/Click"
	DriverService_Fill_FullMethodName             = "/automation.v1.DriverService/Fill"
	DriverService_Swipe_FullMethodName            = "/automation.v1.DriverService/Swipe"
	DriverService_Screenshot_FullMethodName       = "/automation.v1.DriverService/Screenshot"
	DriverService_GetSource_FullMethodName        = "/automation.v1.DriverService/GetSource"
	DriverService_ExecuteScript_FullMethodName    = "/automation.v1.DriverService/ExecuteScript"
	DriverService_GetContexts_FullMethodName      = "/automation.v1.DriverService/GetContexts"
	DriverService_SetContext_FullMethodName       = "/automation.v1.DriverService/SetContext"
	DriverService_GetTelemetry_FullMethodName     = "/automation.v1.DriverService/GetTelemetry"
	DriverService_SetMockLocation_FullMethodName  = "/automation.v1.DriverService/SetMockLocation"
	DriverService_MockBiometrics_FullMethodName   = "/automation.v1.DriverService/MockBiometrics"
)

// DriverServiceClient is the client API for DriverService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DriverServiceClient interface {
	ConnectDriver(ctx context.Context, in *ConnectDriverRequest, opts ...grpc.CallOption) (*ConnectDriverResponse, error)
	DisconnectDriver(ctx context.Context, in *DisconnectDriverRequest, opts ...grpc.CallOption) (*DisconnectDriverResponse, error)
	FindElement(ctx context.Context, in *FindElementRequest, opts ...grpc.CallOption) (*FindElementResponse, error)
	FindElements(ctx context.Context, in *FindElementsRequest, opts ...grpc.CallOption) (*FindElementsResponse, error)
	Click(ctx context.Context, in *ClickRequest, opts ...grpc.CallOption) (*ClickResponse, error)
	Fill(ctx context.Context, in *FillRequest, opts ...grpc.CallOption) (*FillResponse, error)
	Swipe(ctx context.Context, in *SwipeRequest, opts ...grpc.CallOption) (*SwipeResponse, error)
	Screenshot(ctx context.Context, in *ScreenshotRequest, opts ...grpc.CallOption) (*ScreenshotResponse, error)
	GetSource(ctx context.Context, in *GetSourceRequest, opts ...grpc.CallOption) (*GetSourceResponse, error)
	ExecuteScript(ctx context.Context, in *ExecuteScriptRequest, opts ...grpc.CallOption) (*ExecuteScriptResponse, error)
	GetContexts(ctx context.Context, in *GetContextsRequest, opts ...grpc.CallOption) (*GetContextsResponse, error)
	SetContext(ctx context.Context, in *SetContextRequest, opts ...grpc.CallOption) (*SetContextResponse, error)
	GetTelemetry(ctx context.Context, in *GetTelemetryRequest, opts ...grpc.CallOption) (*GetTelemetryResponse, error)
	SetMockLocation(ctx context.Context, in *SetMockLocationRequest, opts ...grpc.CallOption) (*SetMockLocationResponse, error)
	MockBiometrics(ctx context.Context, in *MockBiometricsRequest, opts ...grpc.CallOption) (*MockBiometricsResponse, error)
}

type driverServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDriverServiceClient(cc grpc.ClientConnInterface) DriverServiceClient {
	return &driverServiceClient{cc}
}

func (c *driverServiceClient) ConnectDriver(ctx context.Context, in *ConnectDriverRequest, opts ...grpc.CallOption) (*ConnectDriverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConnectDriverResponse)
	err := c.cc.Invoke(ctx, DriverService_ConnectDriver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) DisconnectDriver(ctx context.Context, in *DisconnectDriverRequest, opts ...grpc.CallOption) (*DisconnectDriverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisconnectDriverResponse)
	err := c.cc.Invoke(ctx, DriverService_DisconnectDriver_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) FindElement(ctx context.Context, in *FindElementRequest, opts ...grpc.CallOption) (*FindElementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindElementResponse)
	err := c.cc.Invoke(ctx, DriverService_FindElement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) FindElements(ctx context.Context, in *FindElementsRequest, opts ...grpc.CallOption) (*FindElementsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindElementsResponse)
	err := c.cc.Invoke(ctx, DriverService_FindElements_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) Click(ctx context.Context, in *ClickRequest, opts ...grpc.CallOption) (*ClickResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClickResponse)
	err := c.cc.Invoke(ctx, DriverService_Click_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) Fill(ctx context.Context, in *FillRequest, opts ...grpc.CallOption) (*FillResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FillResponse)
	err := c.cc.Invoke(ctx, DriverService_Fill_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) Swipe(ctx context.Context, in *SwipeRequest, opts ...grpc.CallOption) (*SwipeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SwipeResponse)
	err := c.cc.Invoke(ctx, DriverService_Swipe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) Screenshot(ctx context.Context, in *ScreenshotRequest, opts ...grpc.CallOption) (*ScreenshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScreenshotResponse)
	err := c.cc.Invoke(ctx, DriverService_Screenshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) GetSource(ctx context.Context, in *GetSourceRequest, opts ...grpc.CallOption) (*GetSourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSourceResponse)
	err := c.cc.Invoke(ctx, DriverService_GetSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) ExecuteScript(ctx context.Context, in *ExecuteScriptRequest, opts ...grpc.CallOption) (*ExecuteScriptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteScriptResponse)
	err := c.cc.Invoke(ctx, DriverService_ExecuteScript_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) GetContexts(ctx context.Context, in *GetContextsRequest, opts ...grpc.CallOption) (*GetContextsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetContextsResponse)
	err := c.cc.Invoke(ctx, DriverService_GetContexts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) SetContext(ctx context.Context, in *SetContextRequest, opts ...grpc.CallOption) (*SetContextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetContextResponse)
	err := c.cc.Invoke(ctx, DriverService_SetContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) GetTelemetry(ctx context.Context, in *GetTelemetryRequest, opts ...grpc.CallOption) (*GetTelemetryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTelemetryResponse)
	err := c.cc.Invoke(ctx, DriverService_GetTelemetry_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) SetMockLocation(ctx context.Context, in *SetMockLocationRequest, opts ...grpc.CallOption) (*SetMockLocationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetMockLocationResponse)
	err := c.cc.Invoke(ctx, DriverService_SetMockLocation_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) MockBiometrics(ctx context.Context, in *MockBiometricsRequest, opts ...grpc.CallOption) (*MockBiometricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MockBiometricsResponse)
	err := c.cc.Invoke(ctx, DriverService_MockBiometrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DriverServiceServer is the server API for DriverService service.
// All implementations must embed UnimplementedDriverServiceServer
// for forward compatibility.
type DriverServiceServer interface {
	ConnectDriver(context.Context, *ConnectDriverRequest) (*ConnectDriverResponse, error)
	DisconnectDriver(context.Context, *DisconnectDriverRequest) (*DisconnectDriverResponse, error)
	FindElement(context.Context, *FindElementRequest) (*FindElementResponse, error)
	FindElements(context.Context, *FindElementsRequest) (*FindElementsResponse, error)
	Click(context.Context, *ClickRequest) (*ClickResponse, error)
	Fill(context.Context, *FillRequest) (*FillResponse, error)
	Swipe(context.Context, *SwipeRequest) (*SwipeResponse, error)
	Screenshot(context.Context, *ScreenshotRequest) (*ScreenshotResponse, error)
	GetSource(context.Context, *GetSourceRequest) (*GetSourceResponse, error)
	ExecuteScript(context.Context, *ExecuteScriptRequest) (*ExecuteScriptResponse, error)
	GetContexts(context.Context, *GetContextsRequest) (*GetContextsResponse, error)
	SetContext(context.Context, *SetContextRequest) (*SetContextResponse, error)
	GetTelemetry(context.Context, *GetTelemetryRequest) (*GetTelemetryResponse, error)
	SetMockLocation(context.Context, *SetMockLocationRequest) (*SetMockLocationResponse, error)
	MockBiometrics(context.Context, *MockBiometricsRequest) (*MockBiometricsResponse, error)
	mustEmbedUnimplementedDriverServiceServer()
}

// UnimplementedDriverServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDriverServiceServer struct{}

func (UnimplementedDriverServiceServer) ConnectDriver(context.Context, *ConnectDriverRequest) (*ConnectDriverResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConnectDriver not implemented")
}
func (UnimplementedDriverServiceServer) DisconnectDriver(context.Context, *DisconnectDriverRequest) (*DisconnectDriverResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DisconnectDriver not implemented")
}
func (UnimplementedDriverServiceServer) FindElement(context.Context, *FindElementRequest) (*FindElementResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindElement not implemented")
}
func (UnimplementedDriverServiceServer) FindElements(context.Context, *FindElementsRequest) (*FindElementsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FindElements not implemented")
}
func (UnimplementedDriverServiceServer) Click(context.Context, *ClickRequest) (*ClickResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Click not implemented")
}
func (UnimplementedDriverServiceServer) Fill(context.Context, *FillRequest) (*FillResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Fill not implemented")
}
func (UnimplementedDriverServiceServer) Swipe(context.Context, *SwipeRequest) (*SwipeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Swipe not implemented")
}
func (UnimplementedDriverServiceServer) Screenshot(context.Context, *ScreenshotRequest) (*ScreenshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Screenshot not implemented")
}
func (UnimplementedDriverServiceServer) GetSource(context.Context, *GetSourceRequest) (*GetSourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSource not implemented")
}
func (UnimplementedDriverServiceServer) ExecuteScript(context.Context, *ExecuteScriptRequest) (*ExecuteScriptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExecuteScript not implemented")
}
func (UnimplementedDriverServiceServer) GetContexts(context.Context, *GetContextsRequest) (*GetContextsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetContexts not implemented")
}
func (UnimplementedDriverServiceServer) SetContext(context.Context, *SetContextRequest) (*SetContextResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetContext not implemented")
}
func (UnimplementedDriverServiceServer) GetTelemetry(context.Context, *GetTelemetryRequest) (*GetTelemetryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTelemetry not implemented")
}
func (UnimplementedDriverServiceServer) SetMockLocation(context.Context, *SetMockLocationRequest) (*SetMockLocationResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetMockLocation not implemented")
}
func (UnimplementedDriverServiceServer) MockBiometrics(context.Context, *MockBiometricsRequest) (*MockBiometricsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MockBiometrics not implemented")
}
func (UnimplementedDriverServiceServer) mustEmbedUnimplementedDriverServiceServer() {}
func (UnimplementedDriverServiceServer) testEmbeddedByValue()                       {}

// UnsafeDriverServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DriverServiceServer will
// result in compilation errors.
type UnsafeDriverServiceServer interface {
	mustEmbedUnimplementedDriverServiceServer()
}

func RegisterDriverServiceServer(s grpc.ServiceRegistrar, srv DriverServiceServer) {
	// If the following call panics, it indicates UnimplementedDriverServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DriverService_ServiceDesc, srv)
}

func _DriverService_ConnectDriver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConnectDriverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).ConnectDriver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_ConnectDriver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).ConnectDriver(ctx, req.(*ConnectDriverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_DisconnectDriver_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisconnectDriverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).DisconnectDriver(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_DisconnectDriver_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).DisconnectDriver(ctx, req.(*DisconnectDriverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_FindElement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindElementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).FindElement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_FindElement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).FindElement(ctx, req.(*FindElementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_FindElements_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindElementsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).FindElements(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_FindElements_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).FindElements(ctx, req.(*FindElementsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_Click_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClickRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).Click(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_Click_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).Click(ctx, req.(*ClickRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_Fill_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FillRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).Fill(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_Fill_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).Fill(ctx, req.(*FillRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_Swipe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SwipeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).Swipe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_Swipe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).Swipe(ctx, req.(*SwipeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_Screenshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScreenshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).Screenshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_Screenshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).Screenshot(ctx, req.(*ScreenshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_GetSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).GetSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_GetSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).GetSource(ctx, req.(*GetSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_ExecuteScript_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteScriptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).ExecuteScript(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_ExecuteScript_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).ExecuteScript(ctx, req.(*ExecuteScriptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_GetContexts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContextsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).GetContexts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_GetContexts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).GetContexts(ctx, req.(*GetContextsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_SetContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).SetContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_SetContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).SetContext(ctx, req.(*SetContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_GetTelemetry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTelemetryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).GetTelemetry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_GetTelemetry_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).GetTelemetry(ctx, req.(*GetTelemetryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_SetMockLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetMockLocationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).SetMockLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_SetMockLocation_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).SetMockLocation(ctx, req.(*SetMockLocationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_MockBiometrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MockBiometricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).MockBiometrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_MockBiometrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).MockBiometrics(ctx, req.(*MockBiometricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DriverService_ServiceDesc is the grpc.ServiceDesc for DriverService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DriverService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "automation.v1.DriverService",
	HandlerType: (*DriverServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ConnectDriver",
			Handler:    _DriverService_ConnectDriver_Handler,
		},
		{
			MethodName: "DisconnectDriver",
			Handler:    _DriverService_DisconnectDriver_Handler,
		},
		{
			MethodName: "FindElement",
			Handler:    _DriverService_FindElement_Handler,
		},
		{
			MethodName: "FindElements",
			Handler:    _DriverService_FindElements_Handler,
		},
		{
			MethodName: "Click",
			Handler:    _DriverService_Click_Handler,
		},
		{
			MethodName: "Fill",
			Handler:    _DriverService_Fill_Handler,
		},
		{
			MethodName: "Swipe",
			Handler:    _DriverService_Swipe_Handler,
		},
		{
			MethodName: "Screenshot",
			Handler:    _DriverService_Screenshot_Handler,
		},
		{
			MethodName: "GetSource",
			Handler:    _DriverService_GetSource_Handler,
		},
		{
			MethodName: "ExecuteScript",
			Handler:    _DriverService_ExecuteScript_Handler,
		},
		{
			MethodName: "GetContexts",
			Handler:    _DriverService_GetContexts_Handler,
		},
		{
			MethodName: "SetContext",
			Handler:    _DriverService_SetContext_Handler,
		},
		{
			MethodName: "GetTelemetry",
			Handler:    _DriverService_GetTelemetry_Handler,
		},
		{
			MethodName: "SetMockLocation",
			Handler:    _DriverService_SetMockLocation_Handler,
		},
		{
			MethodName: "MockBiometrics",
			Handler:    _DriverService_MockBiometrics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/driver.proto",
}
