// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.25.3
// source: proto/driver.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectDriverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	DriverType    string                 `protobuf:"bytes,2,opt,name=driver_type,json=driverType,proto3" json:"driver_type,omitempty"` // e.g. "uiautomator2", "xcuitest"
	DeviceId      string                 `protobuf:"bytes,3,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	Capabilities  map[string]string      `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectDriverRequest) Reset() {
	*x = ConnectDriverRequest{}
	mi := &file_proto_driver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectDriverRequest) ProtoMessage() {}

func (x *ConnectDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectDriverRequest.ProtoReflect.Descriptor instead.
func (*ConnectDriverRequest) Descriptor() ([]byte, []int) {
	return file_proto_driver_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectDriverRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *ConnectDriverRequest) GetDriverType() string {
	if x != nil {
		return x.DriverType
	}
	return ""
}

func (x *ConnectDriverRequest) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *ConnectDriverRequest) GetCapabilities() map[string]string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type ConnectDriverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Connected     bool                   `protobuf:"varint,2,opt,name=connected,proto3" json:"connected,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConnectDriverResponse) Reset() {
	*x = ConnectDriverResponse{}
	mi := &file_proto_driver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectDriverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectDriverResponse) ProtoMessage() {}

func (x *ConnectDriverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectDriverResponse.ProtoReflect.Descriptor instead.
func (*ConnectDriverResponse) Descriptor() ([]byte, []int) {
	return file_proto_driver_proto_rawDescGZIP(), []int{1}
}

func (x *ConnectDriverResponse) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *ConnectDriverResponse) GetConnected() bool {
	if x != nil {
		return x.Connected
	}
	return false
}

func (x *ConnectDriverResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type DisconnectDriverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectDriverRequest) Reset() {
	*x = DisconnectDriverRequest{}
	mi := &file_proto_driver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectDriverRequest) ProtoMessage() {}

func (x *DisconnectDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectDriverRequest.ProtoReflect.Descriptor instead.
func (*DisconnectDriverRequest) Descriptor() ([]byte, []int) {
	return file_proto_driver_proto_rawDescGZIP(), []int{2}
}

func (x *DisconnectDriverRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

type DisconnectDriverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisconnectDriverResponse) Reset() {
	*x = DisconnectDriverResponse{}
	mi := &file_proto_driver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisconnectDriverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisconnectDriverResponse) ProtoMessage() {}

func (x *DisconnectDriverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisconnectDriverResponse.ProtoReflect.Descriptor instead.
func (*DisconnectDriverResponse) Descriptor() ([]byte, []int) {
	return file_proto_driver_proto_rawDescGZIP(), []int{3}
}

func (x *DisconnectDriverResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ClickRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	DriverId string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	// Types that are valid to be assigned to Target:
	//
	//	*ClickRequest_ElementId
	//	*ClickRequest_Coordinates
	Target        isClickRequest_Target `protobuf_oneof:"target"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClickRequest) Reset() {
	*x = ClickRequest{}
	mi := &file_proto_driver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClickRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickRequest) ProtoMessage() {}

func (x *ClickRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickRequest.ProtoReflect.Descriptor instead.
func (*ClickRequest) Descriptor() ([]byte, []int) {
	return file_proto_driver_proto_rawDescGZIP(), []int{4}
}

func (x *ClickRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *ClickRequest) GetTarget() isClickRequest_Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *ClickRequest) GetElementId() string {
	if x != nil {
		if x, ok := x.Target.(*ClickRequest_ElementId); ok {
			return x.ElementId
		}
	}
	return ""
}

func (x *ClickRequest) GetCoordinates() *Point {
	if x != nil {
		if x, ok := x.Target.(*ClickRequest_Coordinates); ok {
			return x.Coordinates
		}
	}
	return nil
}

type isClickRequest_Target interface {
	isClickRequest_Target()
}

type ClickRequest_ElementId struct {
	ElementId string `protobuf:"bytes,2,opt,name=element_id,json=elementId,proto3,oneof"`
}

type ClickRequest_Coordinates struct {
	Coordinates *Point `protobuf:"bytes,3,opt,name=coordinates,proto3,oneof"`
}

func (*ClickRequest_ElementId) isClickRequest_Target() {}

func (*ClickRequest_Coordinates) isClickRequest_Target() {}

type Point struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_proto_driver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_proto_driver_proto_rawDescGZIP(), []int{5}
}

func (x *Point) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Point) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type ClickResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClickResponse) Reset() {
	*x = ClickResponse{}
	mi := &file_proto_driver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClickResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClickResponse) ProtoMessage() {}

func (x *ClickResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClickResponse.ProtoReflect.Descriptor instead.
func (*ClickResponse) Descriptor() ([]byte, []int) {
	return file_proto_driver_proto_rawDescGZIP(), []int{6}
}

func (x *ClickResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ClickResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type FillRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	ElementId     string                 `protobuf:"bytes,2,opt,name=element_id,json=elementId,proto3" json:"element_id,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FillRequest) Reset() {
	*x = FillRequest{}
	mi := &file_proto_driver_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FillRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FillRequest) ProtoMessage() {}

func (x *FillRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FillRequest.ProtoReflect.Descriptor instead.
func (*FillRequest) Descriptor() ([]byte, []int) {
	return file_proto_driver_proto_rawDescGZIP(), []int{7}
}

func (x *FillRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *FillRequest) GetElementId() string {
	if x != nil {
		return x.ElementId
	}
	return ""
}

func (x *FillRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type FillResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FillResponse) Reset() {
	*x = FillResponse{}
	mi := &file_proto_driver_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FillResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FillResponse) ProtoMessage() {}

func (x *FillResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FillResponse.ProtoReflect.Descriptor instead.
func (*FillResponse) Descriptor() ([]byte, []int) {
	return file_proto_driver_proto_rawDescGZIP(), []int{8}
}

func (x *FillResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *FillResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type SwipeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Start         *Point                 `protobuf:"bytes,2,opt,name=start,proto3" json:"start,omitempty"`
	End           *Point                 `protobuf:"bytes,3,opt,name=end,proto3" json:"end,omitempty"`
	DurationMs    int32                  `protobuf:"varint,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwipeRequest) Reset() {
	*x = SwipeRequest{}
	mi := &file_proto_driver_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwipeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwipeRequest) ProtoMessage() {}

func (x *SwipeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwipeRequest.ProtoReflect.Descriptor instead.
func (*SwipeRequest) Descriptor() ([]byte, []int) {
	return file_proto_driver_proto_rawDescGZIP(), []int{9}
}

func (x *SwipeRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *SwipeRequest) GetStart() *Point {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *SwipeRequest) GetEnd() *Point {
	if x != nil {
		return x.End
	}
	return nil
}

func (x *SwipeRequest) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

type SwipeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwipeResponse) Reset() {
	*x = SwipeResponse{}
	mi := &file_proto_driver_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwipeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwipeResponse) ProtoMessage() {}

func (x *SwipeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwipeResponse.ProtoReflect.Descriptor instead.
func (*SwipeResponse) Descriptor() ([]byte, []int) {
	return file_proto_driver_proto_rawDescGZIP(), []int{10}
}

func (x *SwipeResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SwipeResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ScreenshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	ElementId     string                 `protobuf:"bytes,2,opt,name=element_id,json=elementId,proto3" json:"element_id,omitempty"` // optional, to capture specific element bounds
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenshotRequest) Reset() {
	*x = ScreenshotRequest{}
	mi := &file_proto_driver_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenshotRequest) ProtoMessage() {}

func (x *ScreenshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenshotRequest.ProtoReflect.Descriptor instead.
func (*ScreenshotRequest) Descriptor() ([]byte, []int) {
	return file_proto_driver_proto_rawDescGZIP(), []int{11}
}

func (x *ScreenshotRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *ScreenshotRequest) GetElementId() string {
	if x != nil {
		return x.ElementId
	}
	return ""
}

type ScreenshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImageData     []byte                 `protobuf:"bytes,1,opt,name=image_data,json=imageData,proto3" json:"image_data,omitempty"` // PNG format bytes
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenshotResponse) Reset() {
	*x = ScreenshotResponse{}
	mi := &file_proto_driver_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenshotResponse) ProtoMessage() {}

func (x *ScreenshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenshotResponse.ProtoReflect.Descriptor instead.
func (*ScreenshotResponse) Descriptor() ([]byte, []int) {
	return file_proto_driver_proto_rawDescGZIP(), []int{12}
}

func (x *ScreenshotResponse) GetImageData() []byte {
	if x != nil {
		return x.ImageData
	}
	return nil
}

func (x *ScreenshotResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ScreenshotResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type GetSourceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Format        string                 `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"` // e.g. "xml", "json"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSourceRequest) Reset() {
	*x = GetSourceRequest{}
	mi := &file_proto_driver_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSourceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSourceRequest) ProtoMessage() {}

func (x *GetSourceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSourceRequest.ProtoReflect.Descriptor instead.
func (*GetSourceRequest) Descriptor() ([]byte, []int) {
	return file_proto_driver_proto_rawDescGZIP(), []int{13}
}

func (x *GetSourceRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *GetSourceRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

type GetSourceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceData    string                 `protobuf:"bytes,1,opt,name=source_data,json=sourceData,proto3" json:"source_data,omitempty"` // UI tree dump content
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSourceResponse) Reset() {
	*x = GetSourceResponse{}
	mi := &file_proto_driver_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSourceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSourceResponse) ProtoMessage() {}

func (x *GetSourceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSourceResponse.ProtoReflect.Descriptor instead.
func (*GetSourceResponse) Descriptor() ([]byte, []int) {
	return file_proto_driver_proto_rawDescGZIP(), []int{14}
}

func (x *GetSourceResponse) GetSourceData() string {
	if x != nil {
		return x.SourceData
	}
	return ""
}

func (x *GetSourceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetSourceResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type ExecuteScriptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Script        string                 `protobuf:"bytes,2,opt,name=script,proto3" json:"script,omitempty"`
	Arguments     []string               `protobuf:"bytes,3,rep,name=arguments,proto3" json:"arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteScriptRequest) Reset() {
	*x = ExecuteScriptRequest{}
	mi := &file_proto_driver_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteScriptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteScriptRequest) ProtoMessage() {}

func (x *ExecuteScriptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteScriptRequest.ProtoReflect.Descriptor instead.
func (*ExecuteScriptRequest) Descriptor() ([]byte, []int) {
	return file_proto_driver_proto_rawDescGZIP(), []int{15}
}

func (x *ExecuteScriptRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *ExecuteScriptRequest) GetScript() string {
	if x != nil {
		return x.Script
	}
	return ""
}

func (x *ExecuteScriptRequest) GetArguments() []string {
	if x != nil {
		return x.Arguments
	}
	return nil
}

type ExecuteScriptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        string                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteScriptResponse) Reset() {
	*x = ExecuteScriptResponse{}
	mi := &file_proto_driver_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteScriptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteScriptResponse) ProtoMessage() {}

func (x *ExecuteScriptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteScriptResponse.ProtoReflect.Descriptor instead.
func (*ExecuteScriptResponse) Descriptor() ([]byte, []int) {
	return file_proto_driver_proto_rawDescGZIP(), []int{16}
}

func (x *ExecuteScriptResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ExecuteScriptResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ExecuteScriptResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type GetContextsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContextsRequest) Reset() {
	*x = GetContextsRequest{}
	mi := &file_proto_driver_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContextsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContextsRequest) ProtoMessage() {}

func (x *GetContextsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContextsRequest.ProtoReflect.Descriptor instead.
func (*GetContextsRequest) Descriptor() ([]byte, []int) {
	return file_proto_driver_proto_rawDescGZIP(), []int{17}
}

func (x *GetContextsRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

type GetContextsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Contexts      []string               `protobuf:"bytes,1,rep,name=contexts,proto3" json:"contexts,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetContextsResponse) Reset() {
	*x = GetContextsResponse{}
	mi := &file_proto_driver_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetContextsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetContextsResponse) ProtoMessage() {}

func (x *GetContextsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetContextsResponse.ProtoReflect.Descriptor instead.
func (*GetContextsResponse) Descriptor() ([]byte, []int) {
	return file_proto_driver_proto_rawDescGZIP(), []int{18}
}

func (x *GetContextsResponse) GetContexts() []string {
	if x != nil {
		return x.Contexts
	}
	return nil
}

func (x *GetContextsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetContextsResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type SetContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetContextRequest) Reset() {
	*x = SetContextRequest{}
	mi := &file_proto_driver_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetContextRequest) ProtoMessage() {}

func (x *SetContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetContextRequest.ProtoReflect.Descriptor instead.
func (*SetContextRequest) Descriptor() ([]byte, []int) {
	return file_proto_driver_proto_rawDescGZIP(), []int{19}
}

func (x *SetContextRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *SetContextRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SetContextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetContextResponse) Reset() {
	*x = SetContextResponse{}
	mi := &file_proto_driver_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetContextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetContextResponse) ProtoMessage() {}

func (x *SetContextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetContextResponse.ProtoReflect.Descriptor instead.
func (*SetContextResponse) Descriptor() ([]byte, []int) {
	return file_proto_driver_proto_rawDescGZIP(), []int{20}
}

func (x *SetContextResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetContextResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type GetTelemetryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTelemetryRequest) Reset() {
	*x = GetTelemetryRequest{}
	mi := &file_proto_driver_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTelemetryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTelemetryRequest) ProtoMessage() {}

func (x *GetTelemetryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTelemetryRequest.ProtoReflect.Descriptor instead.
func (*GetTelemetryRequest) Descriptor() ([]byte, []int) {
	return file_proto_driver_proto_rawDescGZIP(), []int{21}
}

func (x *GetTelemetryRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

type GetTelemetryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuUsage      float64                `protobuf:"fixed64,1,opt,name=cpu_usage,json=cpuUsage,proto3" json:"cpu_usage,omitempty"`
	RamUsageMb    float64                `protobuf:"fixed64,2,opt,name=ram_usage_mb,json=ramUsageMb,proto3" json:"ram_usage_mb,omitempty"`
	BatteryLevel  int32                  `protobuf:"varint,3,opt,name=battery_level,json=batteryLevel,proto3" json:"battery_level,omitempty"`
	Success       bool                   `protobuf:"varint,4,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTelemetryResponse) Reset() {
	*x = GetTelemetryResponse{}
	mi := &file_proto_driver_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTelemetryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTelemetryResponse) ProtoMessage() {}

func (x *GetTelemetryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTelemetryResponse.ProtoReflect.Descriptor instead.
func (*GetTelemetryResponse) Descriptor() ([]byte, []int) {
	return file_proto_driver_proto_rawDescGZIP(), []int{22}
}

func (x *GetTelemetryResponse) GetCpuUsage() float64 {
	if x != nil {
		return x.CpuUsage
	}
	return 0
}

func (x *GetTelemetryResponse) GetRamUsageMb() float64 {
	if x != nil {
		return x.RamUsageMb
	}
	return 0
}

func (x *GetTelemetryResponse) GetBatteryLevel() int32 {
	if x != nil {
		return x.BatteryLevel
	}
	return 0
}

func (x *GetTelemetryResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetTelemetryResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type SetMockLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Latitude      float64                `protobuf:"fixed64,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     float64                `protobuf:"fixed64,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetMockLocationRequest) Reset() {
	*x = SetMockLocationRequest{}
	mi := &file_proto_driver_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMockLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMockLocationRequest) ProtoMessage() {}

func (x *SetMockLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMockLocationRequest.ProtoReflect.Descriptor instead.
func (*SetMockLocationRequest) Descriptor() ([]byte, []int) {
	return file_proto_driver_proto_rawDescGZIP(), []int{23}
}

func (x *SetMockLocationRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *SetMockLocationRequest) GetLatitude() float64 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *SetMockLocationRequest) GetLongitude() float64 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

type SetMockLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetMockLocationResponse) Reset() {
	*x = SetMockLocationResponse{}
	mi := &file_proto_driver_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetMockLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetMockLocationResponse) ProtoMessage() {}

func (x *SetMockLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetMockLocationResponse.ProtoReflect.Descriptor instead.
func (*SetMockLocationResponse) Descriptor() ([]byte, []int) {
	return file_proto_driver_proto_rawDescGZIP(), []int{24}
}

func (x *SetMockLocationResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetMockLocationResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type MockBiometricsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	EnrollId      int32                  `protobuf:"varint,3,opt,name=enroll_id,json=enrollId,proto3" json:"enroll_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MockBiometricsRequest) Reset() {
	*x = MockBiometricsRequest{}
	mi := &file_proto_driver_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MockBiometricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MockBiometricsRequest) ProtoMessage() {}

func (x *MockBiometricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MockBiometricsRequest.ProtoReflect.Descriptor instead.
func (*MockBiometricsRequest) Descriptor() ([]byte, []int) {
	return file_proto_driver_proto_rawDescGZIP(), []int{25}
}

func (x *MockBiometricsRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *MockBiometricsRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *MockBiometricsRequest) GetEnrollId() int32 {
	if x != nil {
		return x.EnrollId
	}
	return 0
}

type MockBiometricsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MockBiometricsResponse) Reset() {
	*x = MockBiometricsResponse{}
	mi := &file_proto_driver_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MockBiometricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MockBiometricsResponse) ProtoMessage() {}

func (x *MockBiometricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_driver_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MockBiometricsResponse.ProtoReflect.Descriptor instead.
func (*MockBiometricsResponse) Descriptor() ([]byte, []int) {
	return file_proto_driver_proto_rawDescGZIP(), []int{26}
}

func (x *MockBiometricsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *MockBiometricsResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_proto_driver_proto protoreflect.FileDescriptor

const file_proto_driver_proto_rawDesc = "" +
	"\n" +
	"\x12proto/driver.proto\x12\rautomation.v1\x1a\x13proto/locator.proto\"\x8d\x02\n" +
	"\x14ConnectDriverRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x1f\n" +
	"\vdriver_type\x18\x02 \x01(\tR\n" +
	"driverType\x12\x1b\n" +
	"\tdevice_id\x18\x03 \x01(\tR\bdeviceId\x12Y\n" +
	"\fcapabilities\x18\x04 \x03(\v25.automation.v1.ConnectDriverRequest.CapabilitiesEntryR\fcapabilities\x1a?\n" +
	"\x11CapabilitiesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"w\n" +
	"\x15ConnectDriverResponse\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x1c\n" +
	"\tconnected\x18\x02 \x01(\bR\tconnected\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"6\n" +
	"\x17DisconnectDriverRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\"4\n" +
	"\x18DisconnectDriverResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x90\x01\n" +
	"\fClickRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x1f\n" +
	"\n" +
	"element_id\x18\x02 \x01(\tH\x00R\telementId\x128\n" +
	"\vcoordinates\x18\x03 \x01(\v2\x14.automation.v1.PointH\x00R\vcoordinatesB\b\n" +
	"\x06target\"#\n" +
	"\x05Point\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"N\n" +
	"\rClickResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"_\n" +
	"\vFillRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x1d\n" +
	"\n" +
	"element_id\x18\x02 \x01(\tR\telementId\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\"M\n" +
	"\fFillResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"\xa0\x01\n" +
	"\fSwipeRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12*\n" +
	"\x05start\x18\x02 \x01(\v2\x14.automation.v1.PointR\x05start\x12&\n" +
	"\x03end\x18\x03 \x01(\v2\x14.automation.v1.PointR\x03end\x12\x1f\n" +
	"\vduration_ms\x18\x04 \x01(\x05R\n" +
	"durationMs\"N\n" +
	"\rSwipeResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"O\n" +
	"\x11ScreenshotRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x1d\n" +
	"\n" +
	"element_id\x18\x02 \x01(\tR\telementId\"r\n" +
	"\x12ScreenshotResponse\x12\x1d\n" +
	"\n" +
	"image_data\x18\x01 \x01(\fR\timageData\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"G\n" +
	"\x10GetSourceRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x16\n" +
	"\x06format\x18\x02 \x01(\tR\x06format\"s\n" +
	"\x11GetSourceResponse\x12\x1f\n" +
	"\vsource_data\x18\x01 \x01(\tR\n" +
	"sourceData\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"i\n" +
	"\x14ExecuteScriptRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x16\n" +
	"\x06script\x18\x02 \x01(\tR\x06script\x12\x1c\n" +
	"\targuments\x18\x03 \x03(\tR\targuments\"n\n" +
	"\x15ExecuteScriptResponse\x12\x16\n" +
	"\x06result\x18\x01 \x01(\tR\x06result\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"1\n" +
	"\x12GetContextsRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\"p\n" +
	"\x13GetContextsResponse\x12\x1a\n" +
	"\bcontexts\x18\x01 \x03(\tR\bcontexts\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"D\n" +
	"\x11SetContextRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"S\n" +
	"\x12SetContextResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"2\n" +
	"\x13GetTelemetryRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\"\xb9\x01\n" +
	"\x14GetTelemetryResponse\x12\x1b\n" +
	"\tcpu_usage\x18\x01 \x01(\x01R\bcpuUsage\x12 \n" +
	"\fram_usage_mb\x18\x02 \x01(\x01R\n" +
	"ramUsageMb\x12#\n" +
	"\rbattery_level\x18\x03 \x01(\x05R\fbatteryLevel\x12\x18\n" +
	"\asuccess\x18\x04 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\"o\n" +
	"\x16SetMockLocationRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x01R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x01R\tlongitude\"X\n" +
	"\x17SetMockLocationResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"i\n" +
	"\x15MockBiometricsRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\x12\x1b\n" +
	"\tenroll_id\x18\x03 \x01(\x05R\benrollId\"W\n" +
	"\x16MockBiometricsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage2\x8a\n" +
	"\n" +
	"\rDriverService\x12Z\n" +
	"\rConnectDriver\x12#.automation.v1.ConnectDriverRequest\x1a$.automation.v1.ConnectDriverResponse\x12c\n" +
	"\x10DisconnectDriver\x12&.automation.v1.DisconnectDriverRequest\x1a'.automation.v1.DisconnectDriverResponse\x12T\n" +
	"\vFindElement\x12!.automation.v1.FindElementRequest\x1a\".automation.v1.FindElementResponse\x12W\n" +
	"\fFindElements\x12\".automation.v1.FindElementsRequest\x1a#.automation.v1.FindElementsResponse\x12B\n" +
	"\x05Click\x12\x1b.automation.v1.ClickRequest\x1a\x1c.automation.v1.ClickResponse\x12?\n" +
	"\x04Fill\x12\x1a.automation.v1.FillRequest\x1a\x1b.automation.v1.FillResponse\x12B\n" +
	"\x05Swipe\x12\x1b.automation.v1.SwipeRequest\x1a\x1c.automation.v1.SwipeResponse\x12Q\n" +
	"\n" +
	"Screenshot\x12 .automation.v1.ScreenshotRequest\x1a!.automation.v1.ScreenshotResponse\x12N\n" +
	"\tGetSource\x12\x1f.automation.v1.GetSourceRequest\x1a .automation.v1.GetSourceResponse\x12Z\n" +
	"\rExecuteScript\x12#.automation.v1.ExecuteScriptRequest\x1a$.automation.v1.ExecuteScriptResponse\x12T\n" +
	"\vGetContexts\x12!.automation.v1.GetContextsRequest\x1a\".automation.v1.GetContextsResponse\x12Q\n" +
	"\n" +
	"SetContext\x12 .automation.v1.SetContextRequest\x1a!.automation.v1.SetContextResponse\x12W\n" +
	"\fGetTelemetry\x12\".automation.v1.GetTelemetryRequest\x1a#.automation.v1.GetTelemetryResponse\x12`\n" +
	"\x0fSetMockLocation\x12%.automation.v1.SetMockLocationRequest\x1a&.automation.v1.SetMockLocationResponse\x12]\n" +
	"\x0eMockBiometrics\x12$.automation.v1.MockBiometricsRequest\x1a%.automation.v1.MockBiometricsResponseB*Z(github.com/ranjith035/morego/proto/v1;v1b\x06proto3"

var (
	file_proto_driver_proto_rawDescOnce sync.Once
	file_proto_driver_proto_rawDescData []byte
)

func file_proto_driver_proto_rawDescGZIP() []byte {
	file_proto_driver_proto_rawDescOnce.Do(func() {
		file_proto_driver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_driver_proto_rawDesc), len(file_proto_driver_proto_rawDesc)))
	})
	return file_proto_driver_proto_rawDescData
}

var file_proto_driver_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_proto_driver_proto_goTypes = []any{
	(*ConnectDriverRequest)(nil),     // 0: automation.v1.ConnectDriverRequest
	(*ConnectDriverResponse)(nil),    // 1: automation.v1.ConnectDriverResponse
	(*DisconnectDriverRequest)(nil),  // 2: automation.v1.DisconnectDriverRequest
	(*DisconnectDriverResponse)(nil), // 3: automation.v1.DisconnectDriverResponse
	(*ClickRequest)(nil),             // 4: automation.v1.ClickRequest
	(*Point)(nil),                    // 5: automation.v1.Point
	(*ClickResponse)(nil),            // 6: automation.v1.ClickResponse
	(*FillRequest)(nil),              // 7: automation.v1.FillRequest
	(*FillResponse)(nil),             // 8: automation.v1.FillResponse
	(*SwipeRequest)(nil),             // 9: automation.v1.SwipeRequest
	(*SwipeResponse)(nil),            // 10: automation.v1.SwipeResponse
	(*ScreenshotRequest)(nil),        // 11: automation.v1.ScreenshotRequest
	(*ScreenshotResponse)(nil),       // 12: automation.v1.ScreenshotResponse
	(*GetSourceRequest)(nil),         // 13: automation.v1.GetSourceRequest
	(*GetSourceResponse)(nil),        // 14: automation.v1.GetSourceResponse
	(*ExecuteScriptRequest)(nil),     // 15: automation.v1.ExecuteScriptRequest
	(*ExecuteScriptResponse)(nil),    // 16: automation.v1.ExecuteScriptResponse
	(*GetContextsRequest)(nil),       // 17: automation.v1.GetContextsRequest
	(*GetContextsResponse)(nil),      // 18: automation.v1.GetContextsResponse
	(*SetContextRequest)(nil),        // 19: automation.v1.SetContextRequest
	(*SetContextResponse)(nil),       // 20: automation.v1.SetContextResponse
	(*GetTelemetryRequest)(nil),      // 21: automation.v1.GetTelemetryRequest
	(*GetTelemetryResponse)(nil),     // 22: automation.v1.GetTelemetryResponse
	(*SetMockLocationRequest)(nil),   // 23: automation.v1.SetMockLocationRequest
	(*SetMockLocationResponse)(nil),  // 24: automation.v1.SetMockLocationResponse
	(*MockBiometricsRequest)(nil),    // 25: automation.v1.MockBiometricsRequest
	(*MockBiometricsResponse)(nil),   // 26: automation.v1.MockBiometricsResponse
	nil,                              // 27: automation.v1.ConnectDriverRequest.CapabilitiesEntry
	(*FindElementRequest)(nil),       // 28: automation.v1.FindElementRequest
	(*FindElementsRequest)(nil),      // 29: automation.v1.FindElementsRequest
	(*FindElementResponse)(nil),      // 30: automation.v1.FindElementResponse
	(*FindElementsResponse)(nil),     // 31: automation.v1.FindElementsResponse
}
var file_proto_driver_proto_depIdxs = []int32{
	27, // 0: automation.v1.ConnectDriverRequest.capabilities:type_name -> automation.v1.ConnectDriverRequest.CapabilitiesEntry
	5,  // 1: automation.v1.ClickRequest.coordinates:type_name -> automation.v1.Point
	5,  // 2: automation.v1.SwipeRequest.start:type_name -> automation.v1.Point
	5,  // 3: automation.v1.SwipeRequest.end:type_name -> automation.v1.Point
	0,  // 4: automation.v1.DriverService.ConnectDriver:input_type -> automation.v1.ConnectDriverRequest
	2,  // 5: automation.v1.DriverService.DisconnectDriver:input_type -> automation.v1.DisconnectDriverRequest
	28, // 6: automation.v1.DriverService.FindElement:input_type -> automation.v1.FindElementRequest
	29, // 7: automation.v1.DriverService.FindElements:input_type -> automation.v1.FindElementsRequest
	4,  // 8: automation.v1.DriverService.Click:input_type -> automation.v1.ClickRequest
	7,  // 9: automation.v1.DriverService.Fill:input_type -> automation.v1.FillRequest
	9,  // 10: automation.v1.DriverService.Swipe:input_type -> automation.v1.SwipeRequest
	11, // 11: automation.v1.DriverService.Screenshot:input_type -> automation.v1.ScreenshotRequest
	13, // 12: automation.v1.DriverService.GetSource:input_type -> automation.v1.GetSourceRequest
	15, // 13: automation.v1.DriverService.ExecuteScript:input_type -> automation.v1.ExecuteScriptRequest
	17, // 14: automation.v1.DriverService.GetContexts:input_type -> automation.v1.GetContextsRequest
	19, // 15: automation.v1.DriverService.SetContext:input_type -> automation.v1.SetContextRequest
	21, // 16: automation.v1.DriverService.GetTelemetry:input_type -> automation.v1.GetTelemetryRequest
	23, // 17: automation.v1.DriverService.SetMockLocation:input_type -> automation.v1.SetMockLocationRequest
	25, // 18: automation.v1.DriverService.MockBiometrics:input_type -> automation.v1.MockBiometricsRequest
	1,  // 19: automation.v1.DriverService.ConnectDriver:output_type -> automation.v1.ConnectDriverResponse
	3,  // 20: automation.v1.DriverService.DisconnectDriver:output_type -> automation.v1.DisconnectDriverResponse
	30, // 21: automation.v1.DriverService.FindElement:output_type -> automation.v1.FindElementResponse
	31, // 22: automation.v1.DriverService.FindElements:output_type -> automation.v1.FindElementsResponse
	6,  // 23: automation.v1.DriverService.Click:output_type -> automation.v1.ClickResponse
	8,  // 24: automation.v1.DriverService.Fill:output_type -> automation.v1.FillResponse
	10, // 25: automation.v1.DriverService.Swipe:output_type -> automation.v1.SwipeResponse
	12, // 26: automation.v1.DriverService.Screenshot:output_type -> automation.v1.ScreenshotResponse
	14, // 27: automation.v1.DriverService.GetSource:output_type -> automation.v1.GetSourceResponse
	16, // 28: automation.v1.DriverService.ExecuteScript:output_type -> automation.v1.ExecuteScriptResponse
	18, // 29: automation.v1.DriverService.GetContexts:output_type -> automation.v1.GetContextsResponse
	20, // 30: automation.v1.DriverService.SetContext:output_type -> automation.v1.SetContextResponse
	22, // 31: automation.v1.DriverService.GetTelemetry:output_type -> automation.v1.GetTelemetryResponse
	24, // 32: automation.v1.DriverService.SetMockLocation:output_type -> automation.v1.SetMockLocationResponse
	26, // 33: automation.v1.DriverService.MockBiometrics:output_type -> automation.v1.MockBiometricsResponse
	19, // [19:34] is the sub-list for method output_type
	4,  // [4:19] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_proto_driver_proto_init() }
func file_proto_driver_proto_init() {
	if File_proto_driver_proto != nil {
		return
	}
	file_proto_locator_proto_init()
	file_proto_driver_proto_msgTypes[4].OneofWrappers = []any{
		(*ClickRequest_ElementId)(nil),
		(*ClickRequest_Coordinates)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_driver_proto_rawDesc), len(file_proto_driver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_driver_proto_goTypes,
		DependencyIndexes: file_proto_driver_proto_depIdxs,
		MessageInfos:      file_proto_driver_proto_msgTypes,
	}.Build()
	File_proto_driver_proto = out.File
	file_proto_driver_proto_goTypes = nil
	file_proto_driver_proto_depIdxs = nil
}
