// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.25.3
// source: proto/locator.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LocatorStrategy int32

const (
	LocatorStrategy_LOCATOR_STRATEGY_UNSPECIFIED      LocatorStrategy = 0
	LocatorStrategy_LOCATOR_STRATEGY_ACCESSIBILITY_ID LocatorStrategy = 1
	LocatorStrategy_LOCATOR_STRATEGY_TEST_ID          LocatorStrategy = 2
	LocatorStrategy_LOCATOR_STRATEGY_ROLE             LocatorStrategy = 3
	LocatorStrategy_LOCATOR_STRATEGY_TEXT             LocatorStrategy = 4
	LocatorStrategy_LOCATOR_STRATEGY_PLACEHOLDER      LocatorStrategy = 5
	LocatorStrategy_LOCATOR_STRATEGY_LABEL            LocatorStrategy = 6
	LocatorStrategy_LOCATOR_STRATEGY_RESOURCE_ID      LocatorStrategy = 7
	LocatorStrategy_LOCATOR_STRATEGY_XPATH            LocatorStrategy = 8
)

// Enum value maps for LocatorStrategy.
var (
	LocatorStrategy_name = map[int32]string{
		0: "LOCATOR_STRATEGY_UNSPECIFIED",
		1: "LOCATOR_STRATEGY_ACCESSIBILITY_ID",
		2: "LOCATOR_STRATEGY_TEST_ID",
		3: "LOCATOR_STRATEGY_ROLE",
		4: "LOCATOR_STRATEGY_TEXT",
		5: "LOCATOR_STRATEGY_PLACEHOLDER",
		6: "LOCATOR_STRATEGY_LABEL",
		7: "LOCATOR_STRATEGY_RESOURCE_ID",
		8: "LOCATOR_STRATEGY_XPATH",
	}
	LocatorStrategy_value = map[string]int32{
		"LOCATOR_STRATEGY_UNSPECIFIED":      0,
		"LOCATOR_STRATEGY_ACCESSIBILITY_ID": 1,
		"LOCATOR_STRATEGY_TEST_ID":          2,
		"LOCATOR_STRATEGY_ROLE":             3,
		"LOCATOR_STRATEGY_TEXT":             4,
		"LOCATOR_STRATEGY_PLACEHOLDER":      5,
		"LOCATOR_STRATEGY_LABEL":            6,
		"LOCATOR_STRATEGY_RESOURCE_ID":      7,
		"LOCATOR_STRATEGY_XPATH":            8,
	}
)

func (x LocatorStrategy) Enum() *LocatorStrategy {
	p := new(LocatorStrategy)
	*p = x
	return p
}

func (x LocatorStrategy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LocatorStrategy) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_locator_proto_enumTypes[0].Descriptor()
}

func (LocatorStrategy) Type() protoreflect.EnumType {
	return &file_proto_locator_proto_enumTypes[0]
}

func (x LocatorStrategy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LocatorStrategy.Descriptor instead.
func (LocatorStrategy) EnumDescriptor() ([]byte, []int) {
	return file_proto_locator_proto_rawDescGZIP(), []int{0}
}

type RelativeDirection int32

const (
	RelativeDirection_RELATIVE_DIRECTION_UNSPECIFIED RelativeDirection = 0
	RelativeDirection_RELATIVE_DIRECTION_ABOVE       RelativeDirection = 1
	RelativeDirection_RELATIVE_DIRECTION_BELOW       RelativeDirection = 2
	RelativeDirection_RELATIVE_DIRECTION_LEFT_OF     RelativeDirection = 3
	RelativeDirection_RELATIVE_DIRECTION_RIGHT_OF    RelativeDirection = 4
)

// Enum value maps for RelativeDirection.
var (
	RelativeDirection_name = map[int32]string{
		0: "RELATIVE_DIRECTION_UNSPECIFIED",
		1: "RELATIVE_DIRECTION_ABOVE",
		2: "RELATIVE_DIRECTION_BELOW",
		3: "RELATIVE_DIRECTION_LEFT_OF",
		4: "RELATIVE_DIRECTION_RIGHT_OF",
	}
	RelativeDirection_value = map[string]int32{
		"RELATIVE_DIRECTION_UNSPECIFIED": 0,
		"RELATIVE_DIRECTION_ABOVE":       1,
		"RELATIVE_DIRECTION_BELOW":       2,
		"RELATIVE_DIRECTION_LEFT_OF":     3,
		"RELATIVE_DIRECTION_RIGHT_OF":    4,
	}
)

func (x RelativeDirection) Enum() *RelativeDirection {
	p := new(RelativeDirection)
	*p = x
	return p
}

func (x RelativeDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RelativeDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_locator_proto_enumTypes[1].Descriptor()
}

func (RelativeDirection) Type() protoreflect.EnumType {
	return &file_proto_locator_proto_enumTypes[1]
}

func (x RelativeDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RelativeDirection.Descriptor instead.
func (RelativeDirection) EnumDescriptor() ([]byte, []int) {
	return file_proto_locator_proto_rawDescGZIP(), []int{1}
}

type Locator struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Strategy      LocatorStrategy        `protobuf:"varint,1,opt,name=strategy,proto3,enum=automation.v1.LocatorStrategy" json:"strategy,omitempty"`
	Selector      string                 `protobuf:"bytes,2,opt,name=selector,proto3" json:"selector,omitempty"`
	Parent        *Locator               `protobuf:"bytes,3,opt,name=parent,proto3" json:"parent,omitempty"`
	Index         int32                  `protobuf:"varint,4,opt,name=index,proto3" json:"index,omitempty"`
	Constraints   []*RelativeConstraint  `protobuf:"bytes,5,rep,name=constraints,proto3" json:"constraints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Locator) Reset() {
	*x = Locator{}
	mi := &file_proto_locator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Locator) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Locator) ProtoMessage() {}

func (x *Locator) ProtoReflect() protoreflect.Message {
	mi := &file_proto_locator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Locator.ProtoReflect.Descriptor instead.
func (*Locator) Descriptor() ([]byte, []int) {
	return file_proto_locator_proto_rawDescGZIP(), []int{0}
}

func (x *Locator) GetStrategy() LocatorStrategy {
	if x != nil {
		return x.Strategy
	}
	return LocatorStrategy_LOCATOR_STRATEGY_UNSPECIFIED
}

func (x *Locator) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

func (x *Locator) GetParent() *Locator {
	if x != nil {
		return x.Parent
	}
	return nil
}

func (x *Locator) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *Locator) GetConstraints() []*RelativeConstraint {
	if x != nil {
		return x.Constraints
	}
	return nil
}

type RelativeConstraint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Direction     RelativeDirection      `protobuf:"varint,1,opt,name=direction,proto3,enum=automation.v1.RelativeDirection" json:"direction,omitempty"`
	Target        *Locator               `protobuf:"bytes,2,opt,name=target,proto3" json:"target,omitempty"`
	DistancePx    int32                  `protobuf:"varint,3,opt,name=distance_px,json=distancePx,proto3" json:"distance_px,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RelativeConstraint) Reset() {
	*x = RelativeConstraint{}
	mi := &file_proto_locator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RelativeConstraint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RelativeConstraint) ProtoMessage() {}

func (x *RelativeConstraint) ProtoReflect() protoreflect.Message {
	mi := &file_proto_locator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RelativeConstraint.ProtoReflect.Descriptor instead.
func (*RelativeConstraint) Descriptor() ([]byte, []int) {
	return file_proto_locator_proto_rawDescGZIP(), []int{1}
}

func (x *RelativeConstraint) GetDirection() RelativeDirection {
	if x != nil {
		return x.Direction
	}
	return RelativeDirection_RELATIVE_DIRECTION_UNSPECIFIED
}

func (x *RelativeConstraint) GetTarget() *Locator {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *RelativeConstraint) GetDistancePx() int32 {
	if x != nil {
		return x.DistancePx
	}
	return 0
}

type ElementDescriptor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ElementId     string                 `protobuf:"bytes,1,opt,name=element_id,json=elementId,proto3" json:"element_id,omitempty"`
	TagName       string                 `protobuf:"bytes,2,opt,name=tag_name,json=tagName,proto3" json:"tag_name,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	Bounds        *BoundingBox           `protobuf:"bytes,4,opt,name=bounds,proto3" json:"bounds,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,5,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ElementDescriptor) Reset() {
	*x = ElementDescriptor{}
	mi := &file_proto_locator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ElementDescriptor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ElementDescriptor) ProtoMessage() {}

func (x *ElementDescriptor) ProtoReflect() protoreflect.Message {
	mi := &file_proto_locator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ElementDescriptor.ProtoReflect.Descriptor instead.
func (*ElementDescriptor) Descriptor() ([]byte, []int) {
	return file_proto_locator_proto_rawDescGZIP(), []int{2}
}

func (x *ElementDescriptor) GetElementId() string {
	if x != nil {
		return x.ElementId
	}
	return ""
}

func (x *ElementDescriptor) GetTagName() string {
	if x != nil {
		return x.TagName
	}
	return ""
}

func (x *ElementDescriptor) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ElementDescriptor) GetBounds() *BoundingBox {
	if x != nil {
		return x.Bounds
	}
	return nil
}

func (x *ElementDescriptor) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type BoundingBox struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	Width         int32                  `protobuf:"varint,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BoundingBox) Reset() {
	*x = BoundingBox{}
	mi := &file_proto_locator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BoundingBox) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BoundingBox) ProtoMessage() {}

func (x *BoundingBox) ProtoReflect() protoreflect.Message {
	mi := &file_proto_locator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BoundingBox.ProtoReflect.Descriptor instead.
func (*BoundingBox) Descriptor() ([]byte, []int) {
	return file_proto_locator_proto_rawDescGZIP(), []int{3}
}

func (x *BoundingBox) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *BoundingBox) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *BoundingBox) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *BoundingBox) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

type FindElementRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Locator       *Locator               `protobuf:"bytes,2,opt,name=locator,proto3" json:"locator,omitempty"`
	TimeoutMs     int32                  `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindElementRequest) Reset() {
	*x = FindElementRequest{}
	mi := &file_proto_locator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindElementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindElementRequest) ProtoMessage() {}

func (x *FindElementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_locator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindElementRequest.ProtoReflect.Descriptor instead.
func (*FindElementRequest) Descriptor() ([]byte, []int) {
	return file_proto_locator_proto_rawDescGZIP(), []int{4}
}

func (x *FindElementRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *FindElementRequest) GetLocator() *Locator {
	if x != nil {
		return x.Locator
	}
	return nil
}

func (x *FindElementRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type FindElementResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Element       *ElementDescriptor     `protobuf:"bytes,1,opt,name=element,proto3" json:"element,omitempty"`
	Found         bool                   `protobuf:"varint,2,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindElementResponse) Reset() {
	*x = FindElementResponse{}
	mi := &file_proto_locator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindElementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindElementResponse) ProtoMessage() {}

func (x *FindElementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_locator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindElementResponse.ProtoReflect.Descriptor instead.
func (*FindElementResponse) Descriptor() ([]byte, []int) {
	return file_proto_locator_proto_rawDescGZIP(), []int{5}
}

func (x *FindElementResponse) GetElement() *ElementDescriptor {
	if x != nil {
		return x.Element
	}
	return nil
}

func (x *FindElementResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type FindElementsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Locator       *Locator               `protobuf:"bytes,2,opt,name=locator,proto3" json:"locator,omitempty"`
	TimeoutMs     int32                  `protobuf:"varint,3,opt,name=timeout_ms,json=timeoutMs,proto3" json:"timeout_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindElementsRequest) Reset() {
	*x = FindElementsRequest{}
	mi := &file_proto_locator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindElementsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindElementsRequest) ProtoMessage() {}

func (x *FindElementsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_locator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindElementsRequest.ProtoReflect.Descriptor instead.
func (*FindElementsRequest) Descriptor() ([]byte, []int) {
	return file_proto_locator_proto_rawDescGZIP(), []int{6}
}

func (x *FindElementsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *FindElementsRequest) GetLocator() *Locator {
	if x != nil {
		return x.Locator
	}
	return nil
}

func (x *FindElementsRequest) GetTimeoutMs() int32 {
	if x != nil {
		return x.TimeoutMs
	}
	return 0
}

type FindElementsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Elements      []*ElementDescriptor   `protobuf:"bytes,1,rep,name=elements,proto3" json:"elements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindElementsResponse) Reset() {
	*x = FindElementsResponse{}
	mi := &file_proto_locator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindElementsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindElementsResponse) ProtoMessage() {}

func (x *FindElementsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_locator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindElementsResponse.ProtoReflect.Descriptor instead.
func (*FindElementsResponse) Descriptor() ([]byte, []int) {
	return file_proto_locator_proto_rawDescGZIP(), []int{7}
}

func (x *FindElementsResponse) GetElements() []*ElementDescriptor {
	if x != nil {
		return x.Elements
	}
	return nil
}

var File_proto_locator_proto protoreflect.FileDescriptor

const file_proto_locator_proto_rawDesc = "" +
	"\n" +
	"\x13proto/locator.proto\x12\rautomation.v1\"\xec\x01\n" +
	"\aLocator\x12:\n" +
	"\bstrategy\x18\x01 \x01(\x0e2\x1e.automation.v1.LocatorStrategyR\bstrategy\x12\x1a\n" +
	"\bselector\x18\x02 \x01(\tR\bselector\x12.\n" +
	"\x06parent\x18\x03 \x01(\v2\x16.automation.v1.LocatorR\x06parent\x12\x14\n" +
	"\x05index\x18\x04 \x01(\x05R\x05index\x12C\n" +
	"\vconstraints\x18\x05 \x03(\v2!.automation.v1.RelativeConstraintR\vconstraints\"\xa5\x01\n" +
	"\x12RelativeConstraint\x12>\n" +
	"\tdirection\x18\x01 \x01(\x0e2 .automation.v1.RelativeDirectionR\tdirection\x12.\n" +
	"\x06target\x18\x02 \x01(\v2\x16.automation.v1.LocatorR\x06target\x12\x1f\n" +
	"\vdistance_px\x18\x03 \x01(\x05R\n" +
	"distancePx\"\xa6\x02\n" +
	"\x11ElementDescriptor\x12\x1d\n" +
	"\n" +
	"element_id\x18\x01 \x01(\tR\telementId\x12\x19\n" +
	"\btag_name\x18\x02 \x01(\tR\atagName\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x122\n" +
	"\x06bounds\x18\x04 \x01(\v2\x1a.automation.v1.BoundingBoxR\x06bounds\x12P\n" +
	"\n" +
	"attributes\x18\x05 \x03(\v20.automation.v1.ElementDescriptor.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"W\n" +
	"\vBoundingBox\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x05R\x06height\"\x84\x01\n" +
	"\x12FindElementRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x120\n" +
	"\alocator\x18\x02 \x01(\v2\x16.automation.v1.LocatorR\alocator\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\x05R\ttimeoutMs\"g\n" +
	"\x13FindElementResponse\x12:\n" +
	"\aelement\x18\x01 \x01(\v2 .automation.v1.ElementDescriptorR\aelement\x12\x14\n" +
	"\x05found\x18\x02 \x01(\bR\x05found\"\x85\x01\n" +
	"\x13FindElementsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x120\n" +
	"\alocator\x18\x02 \x01(\v2\x16.automation.v1.LocatorR\alocator\x12\x1d\n" +
	"\n" +
	"timeout_ms\x18\x03 \x01(\x05R\ttimeoutMs\"T\n" +
	"\x14FindElementsResponse\x12<\n" +
	"\belements\x18\x01 \x03(\v2 .automation.v1.ElementDescriptorR\belements*\xaa\x02\n" +
	"\x0fLocatorStrategy\x12 \n" +
	"\x1cLOCATOR_STRATEGY_UNSPECIFIED\x10\x00\x12%\n" +
	"!LOCATOR_STRATEGY_ACCESSIBILITY_ID\x10\x01\x12\x1c\n" +
	"\x18LOCATOR_STRATEGY_TEST_ID\x10\x02\x12\x19\n" +
	"\x15LOCATOR_STRATEGY_ROLE\x10\x03\x12\x19\n" +
	"\x15LOCATOR_STRATEGY_TEXT\x10\x04\x12 \n" +
	"\x1cLOCATOR_STRATEGY_PLACEHOLDER\x10\x05\x12\x1a\n" +
	"\x16LOCATOR_STRATEGY_LABEL\x10\x06\x12 \n" +
	"\x1cLOCATOR_STRATEGY_RESOURCE_ID\x10\a\x12\x1a\n" +
	"\x16LOCATOR_STRATEGY_XPATH\x10\b*\xb4\x01\n" +
	"\x11RelativeDirection\x12\"\n" +
	"\x1eRELATIVE_DIRECTION_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18RELATIVE_DIRECTION_ABOVE\x10\x01\x12\x1c\n" +
	"\x18RELATIVE_DIRECTION_BELOW\x10\x02\x12\x1e\n" +
	"\x1aRELATIVE_DIRECTION_LEFT_OF\x10\x03\x12\x1f\n" +
	"\x1bRELATIVE_DIRECTION_RIGHT_OF\x10\x04B*Z(github.com/ranjith035/morego/proto/v1;v1b\x06proto3"

var (
	file_proto_locator_proto_rawDescOnce sync.Once
	file_proto_locator_proto_rawDescData []byte
)

func file_proto_locator_proto_rawDescGZIP() []byte {
	file_proto_locator_proto_rawDescOnce.Do(func() {
		file_proto_locator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_locator_proto_rawDesc), len(file_proto_locator_proto_rawDesc)))
	})
	return file_proto_locator_proto_rawDescData
}

var file_proto_locator_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_locator_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_locator_proto_goTypes = []any{
	(LocatorStrategy)(0),         // 0: automation.v1.LocatorStrategy
	(RelativeDirection)(0),       // 1: automation.v1.RelativeDirection
	(*Locator)(nil),              // 2: automation.v1.Locator
	(*RelativeConstraint)(nil),   // 3: automation.v1.RelativeConstraint
	(*ElementDescriptor)(nil),    // 4: automation.v1.ElementDescriptor
	(*BoundingBox)(nil),          // 5: automation.v1.BoundingBox
	(*FindElementRequest)(nil),   // 6: automation.v1.FindElementRequest
	(*FindElementResponse)(nil),  // 7: automation.v1.FindElementResponse
	(*FindElementsRequest)(nil),  // 8: automation.v1.FindElementsRequest
	(*FindElementsResponse)(nil), // 9: automation.v1.FindElementsResponse
	nil,                          // 10: automation.v1.ElementDescriptor.AttributesEntry
}
var file_proto_locator_proto_depIdxs = []int32{
	0,  // 0: automation.v1.Locator.strategy:type_name -> automation.v1.LocatorStrategy
	2,  // 1: automation.v1.Locator.parent:type_name -> automation.v1.Locator
	3,  // 2: automation.v1.Locator.constraints:type_name -> automation.v1.RelativeConstraint
	1,  // 3: automation.v1.RelativeConstraint.direction:type_name -> automation.v1.RelativeDirection
	2,  // 4: automation.v1.RelativeConstraint.target:type_name -> automation.v1.Locator
	5,  // 5: automation.v1.ElementDescriptor.bounds:type_name -> automation.v1.BoundingBox
	10, // 6: automation.v1.ElementDescriptor.attributes:type_name -> automation.v1.ElementDescriptor.AttributesEntry
	2,  // 7: automation.v1.FindElementRequest.locator:type_name -> automation.v1.Locator
	4,  // 8: automation.v1.FindElementResponse.element:type_name -> automation.v1.ElementDescriptor
	2,  // 9: automation.v1.FindElementsRequest.locator:type_name -> automation.v1.Locator
	4,  // 10: automation.v1.FindElementsResponse.elements:type_name -> automation.v1.ElementDescriptor
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_locator_proto_init() }
func file_proto_locator_proto_init() {
	if File_proto_locator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_locator_proto_rawDesc), len(file_proto_locator_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_locator_proto_goTypes,
		DependencyIndexes: file_proto_locator_proto_depIdxs,
		EnumInfos:         file_proto_locator_proto_enumTypes,
		MessageInfos:      file_proto_locator_proto_msgTypes,
	}.Build()
	File_proto_locator_proto = out.File
	file_proto_locator_proto_goTypes = nil
	file_proto_locator_proto_depIdxs = nil
}
