// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.25.3
// source: proto/plugin.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterPluginRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PluginName       string                 `protobuf:"bytes,1,opt,name=plugin_name,json=pluginName,proto3" json:"plugin_name,omitempty"`
	Version          string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	SubscribedEvents []string               `protobuf:"bytes,3,rep,name=subscribed_events,json=subscribedEvents,proto3" json:"subscribed_events,omitempty"` // e.g. ["before_click", "after_click"]
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *RegisterPluginRequest) Reset() {
	*x = RegisterPluginRequest{}
	mi := &file_proto_plugin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPluginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPluginRequest) ProtoMessage() {}

func (x *RegisterPluginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPluginRequest.ProtoReflect.Descriptor instead.
func (*RegisterPluginRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterPluginRequest) GetPluginName() string {
	if x != nil {
		return x.PluginName
	}
	return ""
}

func (x *RegisterPluginRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterPluginRequest) GetSubscribedEvents() []string {
	if x != nil {
		return x.SubscribedEvents
	}
	return nil
}

type RegisterPluginResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RegistrationId string                 `protobuf:"bytes,1,opt,name=registration_id,json=registrationId,proto3" json:"registration_id,omitempty"`
	Accepted       bool                   `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	Reason         string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterPluginResponse) Reset() {
	*x = RegisterPluginResponse{}
	mi := &file_proto_plugin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterPluginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterPluginResponse) ProtoMessage() {}

func (x *RegisterPluginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterPluginResponse.ProtoReflect.Descriptor instead.
func (*RegisterPluginResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterPluginResponse) GetRegistrationId() string {
	if x != nil {
		return x.RegistrationId
	}
	return ""
}

func (x *RegisterPluginResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *RegisterPluginResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type StreamHooksRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RegistrationId string                 `protobuf:"bytes,1,opt,name=registration_id,json=registrationId,proto3" json:"registration_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *StreamHooksRequest) Reset() {
	*x = StreamHooksRequest{}
	mi := &file_proto_plugin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamHooksRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamHooksRequest) ProtoMessage() {}

func (x *StreamHooksRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamHooksRequest.ProtoReflect.Descriptor instead.
func (*StreamHooksRequest) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{2}
}

func (x *StreamHooksRequest) GetRegistrationId() string {
	if x != nil {
		return x.RegistrationId
	}
	return ""
}

type HookInvocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HookId        string                 `protobuf:"bytes,1,opt,name=hook_id,json=hookId,proto3" json:"hook_id,omitempty"`
	EventName     string                 `protobuf:"bytes,2,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"` // e.g. "before_click"
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Payload       map[string]string      `protobuf:"bytes,4,rep,name=payload,proto3" json:"payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookInvocation) Reset() {
	*x = HookInvocation{}
	mi := &file_proto_plugin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookInvocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookInvocation) ProtoMessage() {}

func (x *HookInvocation) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookInvocation.ProtoReflect.Descriptor instead.
func (*HookInvocation) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{3}
}

func (x *HookInvocation) GetHookId() string {
	if x != nil {
		return x.HookId
	}
	return ""
}

func (x *HookInvocation) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *HookInvocation) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *HookInvocation) GetPayload() map[string]string {
	if x != nil {
		return x.Payload
	}
	return nil
}

type HookResult struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	HookId            string                 `protobuf:"bytes,1,opt,name=hook_id,json=hookId,proto3" json:"hook_id,omitempty"`
	ContinueExecution bool                   `protobuf:"varint,2,opt,name=continue_execution,json=continueExecution,proto3" json:"continue_execution,omitempty"` // Can abort the action if false
	ErrorMessage      string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	ModifiedPayload   map[string]string      `protobuf:"bytes,4,rep,name=modified_payload,json=modifiedPayload,proto3" json:"modified_payload,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Plugins can mutate inputs
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *HookResult) Reset() {
	*x = HookResult{}
	mi := &file_proto_plugin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookResult) ProtoMessage() {}

func (x *HookResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookResult.ProtoReflect.Descriptor instead.
func (*HookResult) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{4}
}

func (x *HookResult) GetHookId() string {
	if x != nil {
		return x.HookId
	}
	return ""
}

func (x *HookResult) GetContinueExecution() bool {
	if x != nil {
		return x.ContinueExecution
	}
	return false
}

func (x *HookResult) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *HookResult) GetModifiedPayload() map[string]string {
	if x != nil {
		return x.ModifiedPayload
	}
	return nil
}

type HookResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HookResultResponse) Reset() {
	*x = HookResultResponse{}
	mi := &file_proto_plugin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HookResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HookResultResponse) ProtoMessage() {}

func (x *HookResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_plugin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HookResultResponse.ProtoReflect.Descriptor instead.
func (*HookResultResponse) Descriptor() ([]byte, []int) {
	return file_proto_plugin_proto_rawDescGZIP(), []int{5}
}

func (x *HookResultResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_plugin_proto protoreflect.FileDescriptor

const file_proto_plugin_proto_rawDesc = "" +
	"\n" +
	"\x12proto/plugin.proto\x12\rautomation.v1\"\x7f\n" +
	"\x15RegisterPluginRequest\x12\x1f\n" +
	"\vplugin_name\x18\x01 \x01(\tR\n" +
	"pluginName\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12+\n" +
	"\x11subscribed_events\x18\x03 \x03(\tR\x10subscribedEvents\"u\n" +
	"\x16RegisterPluginResponse\x12'\n" +
	"\x0fregistration_id\x18\x01 \x01(\tR\x0eregistrationId\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\"=\n" +
	"\x12StreamHooksRequest\x12'\n" +
	"\x0fregistration_id\x18\x01 \x01(\tR\x0eregistrationId\"\xe9\x01\n" +
	"\x0eHookInvocation\x12\x17\n" +
	"\ahook_id\x18\x01 \x01(\tR\x06hookId\x12\x1d\n" +
	"\n" +
	"event_name\x18\x02 \x01(\tR\teventName\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12D\n" +
	"\apayload\x18\x04 \x03(\v2*.automation.v1.HookInvocation.PayloadEntryR\apayload\x1a:\n" +
	"\fPayloadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x98\x02\n" +
	"\n" +
	"HookResult\x12\x17\n" +
	"\ahook_id\x18\x01 \x01(\tR\x06hookId\x12-\n" +
	"\x12continue_execution\x18\x02 \x01(\bR\x11continueExecution\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12Y\n" +
	"\x10modified_payload\x18\x04 \x03(\v2..automation.v1.HookResult.ModifiedPayloadEntryR\x0fmodifiedPayload\x1aB\n" +
	"\x14ModifiedPayloadEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\".\n" +
	"\x12HookResultResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\x93\x02\n" +
	"\rPluginService\x12]\n" +
	"\x0eRegisterPlugin\x12$.automation.v1.RegisterPluginRequest\x1a%.automation.v1.RegisterPluginResponse\x12Q\n" +
	"\vStreamHooks\x12!.automation.v1.StreamHooksRequest\x1a\x1d.automation.v1.HookInvocation0\x01\x12P\n" +
	"\x10SubmitHookResult\x12\x19.automation.v1.HookResult\x1a!.automation.v1.HookResultResponseB*Z(github.com/ranjith035/morego/proto/v1;v1b\x06proto3"

var (
	file_proto_plugin_proto_rawDescOnce sync.Once
	file_proto_plugin_proto_rawDescData []byte
)

func file_proto_plugin_proto_rawDescGZIP() []byte {
	file_proto_plugin_proto_rawDescOnce.Do(func() {
		file_proto_plugin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_plugin_proto_rawDesc), len(file_proto_plugin_proto_rawDesc)))
	})
	return file_proto_plugin_proto_rawDescData
}

var file_proto_plugin_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_plugin_proto_goTypes = []any{
	(*RegisterPluginRequest)(nil),  // 0: automation.v1.RegisterPluginRequest
	(*RegisterPluginResponse)(nil), // 1: automation.v1.RegisterPluginResponse
	(*StreamHooksRequest)(nil),     // 2: automation.v1.StreamHooksRequest
	(*HookInvocation)(nil),         // 3: automation.v1.HookInvocation
	(*HookResult)(nil),             // 4: automation.v1.HookResult
	(*HookResultResponse)(nil),     // 5: automation.v1.HookResultResponse
	nil,                            // 6: automation.v1.HookInvocation.PayloadEntry
	nil,                            // 7: automation.v1.HookResult.ModifiedPayloadEntry
}
var file_proto_plugin_proto_depIdxs = []int32{
	6, // 0: automation.v1.HookInvocation.payload:type_name -> automation.v1.HookInvocation.PayloadEntry
	7, // 1: automation.v1.HookResult.modified_payload:type_name -> automation.v1.HookResult.ModifiedPayloadEntry
	0, // 2: automation.v1.PluginService.RegisterPlugin:input_type -> automation.v1.RegisterPluginRequest
	2, // 3: automation.v1.PluginService.StreamHooks:input_type -> automation.v1.StreamHooksRequest
	4, // 4: automation.v1.PluginService.SubmitHookResult:input_type -> automation.v1.HookResult
	1, // 5: automation.v1.PluginService.RegisterPlugin:output_type -> automation.v1.RegisterPluginResponse
	3, // 6: automation.v1.PluginService.StreamHooks:output_type -> automation.v1.HookInvocation
	5, // 7: automation.v1.PluginService.SubmitHookResult:output_type -> automation.v1.HookResultResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_plugin_proto_init() }
func file_proto_plugin_proto_init() {
	if File_proto_plugin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_plugin_proto_rawDesc), len(file_proto_plugin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_plugin_proto_goTypes,
		DependencyIndexes: file_proto_plugin_proto_depIdxs,
		MessageInfos:      file_proto_plugin_proto_msgTypes,
	}.Build()
	File_proto_plugin_proto = out.File
	file_proto_plugin_proto_goTypes = nil
	file_proto_plugin_proto_depIdxs = nil
}
