// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.25.3
// source: proto/recorder.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED    EventType = 0
	EventType_EVENT_TYPE_TAP            EventType = 1
	EventType_EVENT_TYPE_TEXT_INPUT     EventType = 2
	EventType_EVENT_TYPE_SWIPE          EventType = 3
	EventType_EVENT_TYPE_BACK_BUTTON    EventType = 4
	EventType_EVENT_TYPE_APP_BACKGROUND EventType = 5
	EventType_EVENT_TYPE_APP_FOREGROUND EventType = 6
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_TAP",
		2: "EVENT_TYPE_TEXT_INPUT",
		3: "EVENT_TYPE_SWIPE",
		4: "EVENT_TYPE_BACK_BUTTON",
		5: "EVENT_TYPE_APP_BACKGROUND",
		6: "EVENT_TYPE_APP_FOREGROUND",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":    0,
		"EVENT_TYPE_TAP":            1,
		"EVENT_TYPE_TEXT_INPUT":     2,
		"EVENT_TYPE_SWIPE":          3,
		"EVENT_TYPE_BACK_BUTTON":    4,
		"EVENT_TYPE_APP_BACKGROUND": 5,
		"EVENT_TYPE_APP_FOREGROUND": 6,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_recorder_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_proto_recorder_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_proto_recorder_proto_rawDescGZIP(), []int{0}
}

type StartRecordingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRecordingRequest) Reset() {
	*x = StartRecordingRequest{}
	mi := &file_proto_recorder_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRecordingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRecordingRequest) ProtoMessage() {}

func (x *StartRecordingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recorder_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRecordingRequest.ProtoReflect.Descriptor instead.
func (*StartRecordingRequest) Descriptor() ([]byte, []int) {
	return file_proto_recorder_proto_rawDescGZIP(), []int{0}
}

func (x *StartRecordingRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type StartRecordingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartRecordingResponse) Reset() {
	*x = StartRecordingResponse{}
	mi := &file_proto_recorder_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartRecordingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartRecordingResponse) ProtoMessage() {}

func (x *StartRecordingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recorder_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartRecordingResponse.ProtoReflect.Descriptor instead.
func (*StartRecordingResponse) Descriptor() ([]byte, []int) {
	return file_proto_recorder_proto_rawDescGZIP(), []int{1}
}

func (x *StartRecordingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StartRecordingResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type StopRecordingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRecordingRequest) Reset() {
	*x = StopRecordingRequest{}
	mi := &file_proto_recorder_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRecordingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRecordingRequest) ProtoMessage() {}

func (x *StopRecordingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recorder_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRecordingRequest.ProtoReflect.Descriptor instead.
func (*StopRecordingRequest) Descriptor() ([]byte, []int) {
	return file_proto_recorder_proto_rawDescGZIP(), []int{2}
}

func (x *StopRecordingRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type StopRecordingResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Success           bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	GeneratedCodePath string                 `protobuf:"bytes,2,opt,name=generated_code_path,json=generatedCodePath,proto3" json:"generated_code_path,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *StopRecordingResponse) Reset() {
	*x = StopRecordingResponse{}
	mi := &file_proto_recorder_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRecordingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRecordingResponse) ProtoMessage() {}

func (x *StopRecordingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recorder_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRecordingResponse.ProtoReflect.Descriptor instead.
func (*StopRecordingResponse) Descriptor() ([]byte, []int) {
	return file_proto_recorder_proto_rawDescGZIP(), []int{3}
}

func (x *StopRecordingResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *StopRecordingResponse) GetGeneratedCodePath() string {
	if x != nil {
		return x.GeneratedCodePath
	}
	return ""
}

type StreamEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_proto_recorder_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recorder_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_proto_recorder_proto_rawDescGZIP(), []int{4}
}

func (x *StreamEventsRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type RecordedEvent struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Type        EventType              `protobuf:"varint,1,opt,name=type,proto3,enum=automation.v1.EventType" json:"type,omitempty"`
	TimestampMs int64                  `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*RecordedEvent_Tap
	//	*RecordedEvent_TextInput
	//	*RecordedEvent_Swipe
	Payload       isRecordedEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordedEvent) Reset() {
	*x = RecordedEvent{}
	mi := &file_proto_recorder_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordedEvent) ProtoMessage() {}

func (x *RecordedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recorder_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordedEvent.ProtoReflect.Descriptor instead.
func (*RecordedEvent) Descriptor() ([]byte, []int) {
	return file_proto_recorder_proto_rawDescGZIP(), []int{5}
}

func (x *RecordedEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *RecordedEvent) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *RecordedEvent) GetPayload() isRecordedEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *RecordedEvent) GetTap() *TapPayload {
	if x != nil {
		if x, ok := x.Payload.(*RecordedEvent_Tap); ok {
			return x.Tap
		}
	}
	return nil
}

func (x *RecordedEvent) GetTextInput() *TextInputPayload {
	if x != nil {
		if x, ok := x.Payload.(*RecordedEvent_TextInput); ok {
			return x.TextInput
		}
	}
	return nil
}

func (x *RecordedEvent) GetSwipe() *SwipePayload {
	if x != nil {
		if x, ok := x.Payload.(*RecordedEvent_Swipe); ok {
			return x.Swipe
		}
	}
	return nil
}

type isRecordedEvent_Payload interface {
	isRecordedEvent_Payload()
}

type RecordedEvent_Tap struct {
	Tap *TapPayload `protobuf:"bytes,3,opt,name=tap,proto3,oneof"`
}

type RecordedEvent_TextInput struct {
	TextInput *TextInputPayload `protobuf:"bytes,4,opt,name=text_input,json=textInput,proto3,oneof"`
}

type RecordedEvent_Swipe struct {
	Swipe *SwipePayload `protobuf:"bytes,5,opt,name=swipe,proto3,oneof"`
}

func (*RecordedEvent_Tap) isRecordedEvent_Payload() {}

func (*RecordedEvent_TextInput) isRecordedEvent_Payload() {}

func (*RecordedEvent_Swipe) isRecordedEvent_Payload() {}

type TapPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	TargetLocator *Locator               `protobuf:"bytes,3,opt,name=target_locator,json=targetLocator,proto3" json:"target_locator,omitempty"` // Best matching locator generated by locator ranking
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TapPayload) Reset() {
	*x = TapPayload{}
	mi := &file_proto_recorder_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TapPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TapPayload) ProtoMessage() {}

func (x *TapPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recorder_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TapPayload.ProtoReflect.Descriptor instead.
func (*TapPayload) Descriptor() ([]byte, []int) {
	return file_proto_recorder_proto_rawDescGZIP(), []int{6}
}

func (x *TapPayload) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *TapPayload) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *TapPayload) GetTargetLocator() *Locator {
	if x != nil {
		return x.TargetLocator
	}
	return nil
}

type TextInputPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ElementId     string                 `protobuf:"bytes,1,opt,name=element_id,json=elementId,proto3" json:"element_id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	TargetLocator *Locator               `protobuf:"bytes,3,opt,name=target_locator,json=targetLocator,proto3" json:"target_locator,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TextInputPayload) Reset() {
	*x = TextInputPayload{}
	mi := &file_proto_recorder_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TextInputPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextInputPayload) ProtoMessage() {}

func (x *TextInputPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recorder_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextInputPayload.ProtoReflect.Descriptor instead.
func (*TextInputPayload) Descriptor() ([]byte, []int) {
	return file_proto_recorder_proto_rawDescGZIP(), []int{7}
}

func (x *TextInputPayload) GetElementId() string {
	if x != nil {
		return x.ElementId
	}
	return ""
}

func (x *TextInputPayload) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *TextInputPayload) GetTargetLocator() *Locator {
	if x != nil {
		return x.TargetLocator
	}
	return nil
}

type SwipePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartX        int32                  `protobuf:"varint,1,opt,name=start_x,json=startX,proto3" json:"start_x,omitempty"`
	StartY        int32                  `protobuf:"varint,2,opt,name=start_y,json=startY,proto3" json:"start_y,omitempty"`
	EndX          int32                  `protobuf:"varint,3,opt,name=end_x,json=endX,proto3" json:"end_x,omitempty"`
	EndY          int32                  `protobuf:"varint,4,opt,name=end_y,json=endY,proto3" json:"end_y,omitempty"`
	DurationMs    int32                  `protobuf:"varint,5,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SwipePayload) Reset() {
	*x = SwipePayload{}
	mi := &file_proto_recorder_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SwipePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SwipePayload) ProtoMessage() {}

func (x *SwipePayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_recorder_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SwipePayload.ProtoReflect.Descriptor instead.
func (*SwipePayload) Descriptor() ([]byte, []int) {
	return file_proto_recorder_proto_rawDescGZIP(), []int{8}
}

func (x *SwipePayload) GetStartX() int32 {
	if x != nil {
		return x.StartX
	}
	return 0
}

func (x *SwipePayload) GetStartY() int32 {
	if x != nil {
		return x.StartY
	}
	return 0
}

func (x *SwipePayload) GetEndX() int32 {
	if x != nil {
		return x.EndX
	}
	return 0
}

func (x *SwipePayload) GetEndY() int32 {
	if x != nil {
		return x.EndY
	}
	return 0
}

func (x *SwipePayload) GetDurationMs() int32 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

var File_proto_recorder_proto protoreflect.FileDescriptor

const file_proto_recorder_proto_rawDesc = "" +
	"\n" +
	"\x14proto/recorder.proto\x12\rautomation.v1\x1a\x13proto/locator.proto\"6\n" +
	"\x15StartRecordingRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"W\n" +
	"\x16StartRecordingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\"5\n" +
	"\x14StopRecordingRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"a\n" +
	"\x15StopRecordingResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12.\n" +
	"\x13generated_code_path\x18\x02 \x01(\tR\x11generatedCodePath\"4\n" +
	"\x13StreamEventsRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x91\x02\n" +
	"\rRecordedEvent\x12,\n" +
	"\x04type\x18\x01 \x01(\x0e2\x18.automation.v1.EventTypeR\x04type\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\x12-\n" +
	"\x03tap\x18\x03 \x01(\v2\x19.automation.v1.TapPayloadH\x00R\x03tap\x12@\n" +
	"\n" +
	"text_input\x18\x04 \x01(\v2\x1f.automation.v1.TextInputPayloadH\x00R\ttextInput\x123\n" +
	"\x05swipe\x18\x05 \x01(\v2\x1b.automation.v1.SwipePayloadH\x00R\x05swipeB\t\n" +
	"\apayload\"g\n" +
	"\n" +
	"TapPayload\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\x12=\n" +
	"\x0etarget_locator\x18\x03 \x01(\v2\x16.automation.v1.LocatorR\rtargetLocator\"\x84\x01\n" +
	"\x10TextInputPayload\x12\x1d\n" +
	"\n" +
	"element_id\x18\x01 \x01(\tR\telementId\x12\x12\n" +
	"\x04text\x18\x02 \x01(\tR\x04text\x12=\n" +
	"\x0etarget_locator\x18\x03 \x01(\v2\x16.automation.v1.LocatorR\rtargetLocator\"\x8b\x01\n" +
	"\fSwipePayload\x12\x17\n" +
	"\astart_x\x18\x01 \x01(\x05R\x06startX\x12\x17\n" +
	"\astart_y\x18\x02 \x01(\x05R\x06startY\x12\x13\n" +
	"\x05end_x\x18\x03 \x01(\x05R\x04endX\x12\x13\n" +
	"\x05end_y\x18\x04 \x01(\x05R\x04endY\x12\x1f\n" +
	"\vduration_ms\x18\x05 \x01(\x05R\n" +
	"durationMs*\xc6\x01\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eEVENT_TYPE_TAP\x10\x01\x12\x19\n" +
	"\x15EVENT_TYPE_TEXT_INPUT\x10\x02\x12\x14\n" +
	"\x10EVENT_TYPE_SWIPE\x10\x03\x12\x1a\n" +
	"\x16EVENT_TYPE_BACK_BUTTON\x10\x04\x12\x1d\n" +
	"\x19EVENT_TYPE_APP_BACKGROUND\x10\x05\x12\x1d\n" +
	"\x19EVENT_TYPE_APP_FOREGROUND\x10\x062\xa0\x02\n" +
	"\x0fRecorderService\x12]\n" +
	"\x0eStartRecording\x12$.automation.v1.StartRecordingRequest\x1a%.automation.v1.StartRecordingResponse\x12Z\n" +
	"\rStopRecording\x12#.automation.v1.StopRecordingRequest\x1a$.automation.v1.StopRecordingResponse\x12R\n" +
	"\fStreamEvents\x12\".automation.v1.StreamEventsRequest\x1a\x1c.automation.v1.RecordedEvent0\x01B*Z(github.com/ranjith035/morego/proto/v1;v1b\x06proto3"

var (
	file_proto_recorder_proto_rawDescOnce sync.Once
	file_proto_recorder_proto_rawDescData []byte
)

func file_proto_recorder_proto_rawDescGZIP() []byte {
	file_proto_recorder_proto_rawDescOnce.Do(func() {
		file_proto_recorder_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_recorder_proto_rawDesc), len(file_proto_recorder_proto_rawDesc)))
	})
	return file_proto_recorder_proto_rawDescData
}

var file_proto_recorder_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_recorder_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_recorder_proto_goTypes = []any{
	(EventType)(0),                 // 0: automation.v1.EventType
	(*StartRecordingRequest)(nil),  // 1: automation.v1.StartRecordingRequest
	(*StartRecordingResponse)(nil), // 2: automation.v1.StartRecordingResponse
	(*StopRecordingRequest)(nil),   // 3: automation.v1.StopRecordingRequest
	(*StopRecordingResponse)(nil),  // 4: automation.v1.StopRecordingResponse
	(*StreamEventsRequest)(nil),    // 5: automation.v1.StreamEventsRequest
	(*RecordedEvent)(nil),          // 6: automation.v1.RecordedEvent
	(*TapPayload)(nil),             // 7: automation.v1.TapPayload
	(*TextInputPayload)(nil),       // 8: automation.v1.TextInputPayload
	(*SwipePayload)(nil),           // 9: automation.v1.SwipePayload
	(*Locator)(nil),                // 10: automation.v1.Locator
}
var file_proto_recorder_proto_depIdxs = []int32{
	0,  // 0: automation.v1.RecordedEvent.type:type_name -> automation.v1.EventType
	7,  // 1: automation.v1.RecordedEvent.tap:type_name -> automation.v1.TapPayload
	8,  // 2: automation.v1.RecordedEvent.text_input:type_name -> automation.v1.TextInputPayload
	9,  // 3: automation.v1.RecordedEvent.swipe:type_name -> automation.v1.SwipePayload
	10, // 4: automation.v1.TapPayload.target_locator:type_name -> automation.v1.Locator
	10, // 5: automation.v1.TextInputPayload.target_locator:type_name -> automation.v1.Locator
	1,  // 6: automation.v1.RecorderService.StartRecording:input_type -> automation.v1.StartRecordingRequest
	3,  // 7: automation.v1.RecorderService.StopRecording:input_type -> automation.v1.StopRecordingRequest
	5,  // 8: automation.v1.RecorderService.StreamEvents:input_type -> automation.v1.StreamEventsRequest
	2,  // 9: automation.v1.RecorderService.StartRecording:output_type -> automation.v1.StartRecordingResponse
	4,  // 10: automation.v1.RecorderService.StopRecording:output_type -> automation.v1.StopRecordingResponse
	6,  // 11: automation.v1.RecorderService.StreamEvents:output_type -> automation.v1.RecordedEvent
	9,  // [9:12] is the sub-list for method output_type
	6,  // [6:9] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_recorder_proto_init() }
func file_proto_recorder_proto_init() {
	if File_proto_recorder_proto != nil {
		return
	}
	file_proto_locator_proto_init()
	file_proto_recorder_proto_msgTypes[5].OneofWrappers = []any{
		(*RecordedEvent_Tap)(nil),
		(*RecordedEvent_TextInput)(nil),
		(*RecordedEvent_Swipe)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_recorder_proto_rawDesc), len(file_proto_recorder_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_recorder_proto_goTypes,
		DependencyIndexes: file_proto_recorder_proto_depIdxs,
		EnumInfos:         file_proto_recorder_proto_enumTypes,
		MessageInfos:      file_proto_recorder_proto_msgTypes,
	}.Build()
	File_proto_recorder_proto = out.File
	file_proto_recorder_proto_goTypes = nil
	file_proto_recorder_proto_depIdxs = nil
}
