// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v4.25.3
// source: proto/reporter.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ReporterService_ReportSuiteStart_FullMethodName   = "/automation.v1.ReporterService/ReportSuiteStart"
	ReporterService_ReportTestStart_FullMethodName    = "/automation.v1.ReporterService/ReportTestStart"
	ReporterService_ReportTestEnd_FullMethodName      = "/automation.v1.ReporterService/ReportTestEnd"
	ReporterService_ReportSuiteEnd_FullMethodName     = "/automation.v1.ReporterService/ReportSuiteEnd"
	ReporterService_UploadTestArtifact_FullMethodName = "/automation.v1.ReporterService/UploadTestArtifact"
)

// ReporterServiceClient is the client API for ReporterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReporterServiceClient interface {
	ReportSuiteStart(ctx context.Context, in *ReportSuiteStartRequest, opts ...grpc.CallOption) (*ReportSuiteStartResponse, error)
	ReportTestStart(ctx context.Context, in *ReportTestStartRequest, opts ...grpc.CallOption) (*ReportTestStartResponse, error)
	ReportTestEnd(ctx context.Context, in *ReportTestEndRequest, opts ...grpc.CallOption) (*ReportTestEndResponse, error)
	ReportSuiteEnd(ctx context.Context, in *ReportSuiteEndRequest, opts ...grpc.CallOption) (*ReportSuiteEndResponse, error)
	UploadTestArtifact(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadArtifactRequest, UploadArtifactResponse], error)
}

type reporterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewReporterServiceClient(cc grpc.ClientConnInterface) ReporterServiceClient {
	return &reporterServiceClient{cc}
}

func (c *reporterServiceClient) ReportSuiteStart(ctx context.Context, in *ReportSuiteStartRequest, opts ...grpc.CallOption) (*ReportSuiteStartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportSuiteStartResponse)
	err := c.cc.Invoke(ctx, ReporterService_ReportSuiteStart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reporterServiceClient) ReportTestStart(ctx context.Context, in *ReportTestStartRequest, opts ...grpc.CallOption) (*ReportTestStartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportTestStartResponse)
	err := c.cc.Invoke(ctx, ReporterService_ReportTestStart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reporterServiceClient) ReportTestEnd(ctx context.Context, in *ReportTestEndRequest, opts ...grpc.CallOption) (*ReportTestEndResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportTestEndResponse)
	err := c.cc.Invoke(ctx, ReporterService_ReportTestEnd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reporterServiceClient) ReportSuiteEnd(ctx context.Context, in *ReportSuiteEndRequest, opts ...grpc.CallOption) (*ReportSuiteEndResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportSuiteEndResponse)
	err := c.cc.Invoke(ctx, ReporterService_ReportSuiteEnd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *reporterServiceClient) UploadTestArtifact(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadArtifactRequest, UploadArtifactResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ReporterService_ServiceDesc.Streams[0], ReporterService_UploadTestArtifact_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadArtifactRequest, UploadArtifactResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ReporterService_UploadTestArtifactClient = grpc.ClientStreamingClient[UploadArtifactRequest, UploadArtifactResponse]

// ReporterServiceServer is the server API for ReporterService service.
// All implementations must embed UnimplementedReporterServiceServer
// for forward compatibility.
type ReporterServiceServer interface {
	ReportSuiteStart(context.Context, *ReportSuiteStartRequest) (*ReportSuiteStartResponse, error)
	ReportTestStart(context.Context, *ReportTestStartRequest) (*ReportTestStartResponse, error)
	ReportTestEnd(context.Context, *ReportTestEndRequest) (*ReportTestEndResponse, error)
	ReportSuiteEnd(context.Context, *ReportSuiteEndRequest) (*ReportSuiteEndResponse, error)
	UploadTestArtifact(grpc.ClientStreamingServer[UploadArtifactRequest, UploadArtifactResponse]) error
	mustEmbedUnimplementedReporterServiceServer()
}

// UnimplementedReporterServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedReporterServiceServer struct{}

func (UnimplementedReporterServiceServer) ReportSuiteStart(context.Context, *ReportSuiteStartRequest) (*ReportSuiteStartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportSuiteStart not implemented")
}
func (UnimplementedReporterServiceServer) ReportTestStart(context.Context, *ReportTestStartRequest) (*ReportTestStartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportTestStart not implemented")
}
func (UnimplementedReporterServiceServer) ReportTestEnd(context.Context, *ReportTestEndRequest) (*ReportTestEndResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportTestEnd not implemented")
}
func (UnimplementedReporterServiceServer) ReportSuiteEnd(context.Context, *ReportSuiteEndRequest) (*ReportSuiteEndResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportSuiteEnd not implemented")
}
func (UnimplementedReporterServiceServer) UploadTestArtifact(grpc.ClientStreamingServer[UploadArtifactRequest, UploadArtifactResponse]) error {
	return status.Error(codes.Unimplemented, "method UploadTestArtifact not implemented")
}
func (UnimplementedReporterServiceServer) mustEmbedUnimplementedReporterServiceServer() {}
func (UnimplementedReporterServiceServer) testEmbeddedByValue()                         {}

// UnsafeReporterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReporterServiceServer will
// result in compilation errors.
type UnsafeReporterServiceServer interface {
	mustEmbedUnimplementedReporterServiceServer()
}

func RegisterReporterServiceServer(s grpc.ServiceRegistrar, srv ReporterServiceServer) {
	// If the following call panics, it indicates UnimplementedReporterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ReporterService_ServiceDesc, srv)
}

func _ReporterService_ReportSuiteStart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportSuiteStartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReporterServiceServer).ReportSuiteStart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReporterService_ReportSuiteStart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReporterServiceServer).ReportSuiteStart(ctx, req.(*ReportSuiteStartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReporterService_ReportTestStart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportTestStartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReporterServiceServer).ReportTestStart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReporterService_ReportTestStart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReporterServiceServer).ReportTestStart(ctx, req.(*ReportTestStartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReporterService_ReportTestEnd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportTestEndRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReporterServiceServer).ReportTestEnd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReporterService_ReportTestEnd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReporterServiceServer).ReportTestEnd(ctx, req.(*ReportTestEndRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReporterService_ReportSuiteEnd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportSuiteEndRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReporterServiceServer).ReportSuiteEnd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ReporterService_ReportSuiteEnd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReporterServiceServer).ReportSuiteEnd(ctx, req.(*ReportSuiteEndRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ReporterService_UploadTestArtifact_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ReporterServiceServer).UploadTestArtifact(&grpc.GenericServerStream[UploadArtifactRequest, UploadArtifactResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ReporterService_UploadTestArtifactServer = grpc.ClientStreamingServer[UploadArtifactRequest, UploadArtifactResponse]

// ReporterService_ServiceDesc is the grpc.ServiceDesc for ReporterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReporterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "automation.v1.ReporterService",
	HandlerType: (*ReporterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportSuiteStart",
			Handler:    _ReporterService_ReportSuiteStart_Handler,
		},
		{
			MethodName: "ReportTestStart",
			Handler:    _ReporterService_ReportTestStart_Handler,
		},
		{
			MethodName: "ReportTestEnd",
			Handler:    _ReporterService_ReportTestEnd_Handler,
		},
		{
			MethodName: "ReportSuiteEnd",
			Handler:    _ReporterService_ReportSuiteEnd_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadTestArtifact",
			Handler:       _ReporterService_UploadTestArtifact_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "proto/reporter.proto",
}
