// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v4.25.3
// source: proto/reporter.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TestStatus int32

const (
	TestStatus_TEST_STATUS_UNSPECIFIED TestStatus = 0
	TestStatus_TEST_STATUS_PASSED      TestStatus = 1
	TestStatus_TEST_STATUS_FAILED      TestStatus = 2
	TestStatus_TEST_STATUS_SKIPPED     TestStatus = 3
)

// Enum value maps for TestStatus.
var (
	TestStatus_name = map[int32]string{
		0: "TEST_STATUS_UNSPECIFIED",
		1: "TEST_STATUS_PASSED",
		2: "TEST_STATUS_FAILED",
		3: "TEST_STATUS_SKIPPED",
	}
	TestStatus_value = map[string]int32{
		"TEST_STATUS_UNSPECIFIED": 0,
		"TEST_STATUS_PASSED":      1,
		"TEST_STATUS_FAILED":      2,
		"TEST_STATUS_SKIPPED":     3,
	}
)

func (x TestStatus) Enum() *TestStatus {
	p := new(TestStatus)
	*p = x
	return p
}

func (x TestStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TestStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_reporter_proto_enumTypes[0].Descriptor()
}

func (TestStatus) Type() protoreflect.EnumType {
	return &file_proto_reporter_proto_enumTypes[0]
}

func (x TestStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TestStatus.Descriptor instead.
func (TestStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_reporter_proto_rawDescGZIP(), []int{0}
}

type ArtifactType int32

const (
	ArtifactType_ARTIFACT_TYPE_UNSPECIFIED ArtifactType = 0
	ArtifactType_ARTIFACT_TYPE_SCREENSHOT  ArtifactType = 1
	ArtifactType_ARTIFACT_TYPE_VIDEO       ArtifactType = 2
	ArtifactType_ARTIFACT_TYPE_LOG         ArtifactType = 3
	ArtifactType_ARTIFACT_TYPE_TRACE       ArtifactType = 4
)

// Enum value maps for ArtifactType.
var (
	ArtifactType_name = map[int32]string{
		0: "ARTIFACT_TYPE_UNSPECIFIED",
		1: "ARTIFACT_TYPE_SCREENSHOT",
		2: "ARTIFACT_TYPE_VIDEO",
		3: "ARTIFACT_TYPE_LOG",
		4: "ARTIFACT_TYPE_TRACE",
	}
	ArtifactType_value = map[string]int32{
		"ARTIFACT_TYPE_UNSPECIFIED": 0,
		"ARTIFACT_TYPE_SCREENSHOT":  1,
		"ARTIFACT_TYPE_VIDEO":       2,
		"ARTIFACT_TYPE_LOG":         3,
		"ARTIFACT_TYPE_TRACE":       4,
	}
)

func (x ArtifactType) Enum() *ArtifactType {
	p := new(ArtifactType)
	*p = x
	return p
}

func (x ArtifactType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ArtifactType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_reporter_proto_enumTypes[1].Descriptor()
}

func (ArtifactType) Type() protoreflect.EnumType {
	return &file_proto_reporter_proto_enumTypes[1]
}

func (x ArtifactType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ArtifactType.Descriptor instead.
func (ArtifactType) EnumDescriptor() ([]byte, []int) {
	return file_proto_reporter_proto_rawDescGZIP(), []int{1}
}

type ReportSuiteStartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SuiteName     string                 `protobuf:"bytes,1,opt,name=suite_name,json=suiteName,proto3" json:"suite_name,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportSuiteStartRequest) Reset() {
	*x = ReportSuiteStartRequest{}
	mi := &file_proto_reporter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportSuiteStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportSuiteStartRequest) ProtoMessage() {}

func (x *ReportSuiteStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reporter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportSuiteStartRequest.ProtoReflect.Descriptor instead.
func (*ReportSuiteStartRequest) Descriptor() ([]byte, []int) {
	return file_proto_reporter_proto_rawDescGZIP(), []int{0}
}

func (x *ReportSuiteStartRequest) GetSuiteName() string {
	if x != nil {
		return x.SuiteName
	}
	return ""
}

func (x *ReportSuiteStartRequest) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type ReportSuiteStartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SuiteRunId    string                 `protobuf:"bytes,1,opt,name=suite_run_id,json=suiteRunId,proto3" json:"suite_run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportSuiteStartResponse) Reset() {
	*x = ReportSuiteStartResponse{}
	mi := &file_proto_reporter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportSuiteStartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportSuiteStartResponse) ProtoMessage() {}

func (x *ReportSuiteStartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reporter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportSuiteStartResponse.ProtoReflect.Descriptor instead.
func (*ReportSuiteStartResponse) Descriptor() ([]byte, []int) {
	return file_proto_reporter_proto_rawDescGZIP(), []int{1}
}

func (x *ReportSuiteStartResponse) GetSuiteRunId() string {
	if x != nil {
		return x.SuiteRunId
	}
	return ""
}

type ReportTestStartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SuiteRunId    string                 `protobuf:"bytes,1,opt,name=suite_run_id,json=suiteRunId,proto3" json:"suite_run_id,omitempty"`
	TestName      string                 `protobuf:"bytes,2,opt,name=test_name,json=testName,proto3" json:"test_name,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTestStartRequest) Reset() {
	*x = ReportTestStartRequest{}
	mi := &file_proto_reporter_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTestStartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTestStartRequest) ProtoMessage() {}

func (x *ReportTestStartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reporter_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTestStartRequest.ProtoReflect.Descriptor instead.
func (*ReportTestStartRequest) Descriptor() ([]byte, []int) {
	return file_proto_reporter_proto_rawDescGZIP(), []int{2}
}

func (x *ReportTestStartRequest) GetSuiteRunId() string {
	if x != nil {
		return x.SuiteRunId
	}
	return ""
}

func (x *ReportTestStartRequest) GetTestName() string {
	if x != nil {
		return x.TestName
	}
	return ""
}

func (x *ReportTestStartRequest) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type ReportTestStartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestRunId     string                 `protobuf:"bytes,1,opt,name=test_run_id,json=testRunId,proto3" json:"test_run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTestStartResponse) Reset() {
	*x = ReportTestStartResponse{}
	mi := &file_proto_reporter_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTestStartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTestStartResponse) ProtoMessage() {}

func (x *ReportTestStartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reporter_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTestStartResponse.ProtoReflect.Descriptor instead.
func (*ReportTestStartResponse) Descriptor() ([]byte, []int) {
	return file_proto_reporter_proto_rawDescGZIP(), []int{3}
}

func (x *ReportTestStartResponse) GetTestRunId() string {
	if x != nil {
		return x.TestRunId
	}
	return ""
}

type ReportTestEndRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestRunId     string                 `protobuf:"bytes,1,opt,name=test_run_id,json=testRunId,proto3" json:"test_run_id,omitempty"`
	Status        TestStatus             `protobuf:"varint,2,opt,name=status,proto3,enum=automation.v1.TestStatus" json:"status,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	StackTrace    string                 `protobuf:"bytes,4,opt,name=stack_trace,json=stackTrace,proto3" json:"stack_trace,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,5,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTestEndRequest) Reset() {
	*x = ReportTestEndRequest{}
	mi := &file_proto_reporter_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTestEndRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTestEndRequest) ProtoMessage() {}

func (x *ReportTestEndRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reporter_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTestEndRequest.ProtoReflect.Descriptor instead.
func (*ReportTestEndRequest) Descriptor() ([]byte, []int) {
	return file_proto_reporter_proto_rawDescGZIP(), []int{4}
}

func (x *ReportTestEndRequest) GetTestRunId() string {
	if x != nil {
		return x.TestRunId
	}
	return ""
}

func (x *ReportTestEndRequest) GetStatus() TestStatus {
	if x != nil {
		return x.Status
	}
	return TestStatus_TEST_STATUS_UNSPECIFIED
}

func (x *ReportTestEndRequest) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *ReportTestEndRequest) GetStackTrace() string {
	if x != nil {
		return x.StackTrace
	}
	return ""
}

func (x *ReportTestEndRequest) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type ReportTestEndResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportTestEndResponse) Reset() {
	*x = ReportTestEndResponse{}
	mi := &file_proto_reporter_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportTestEndResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportTestEndResponse) ProtoMessage() {}

func (x *ReportTestEndResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reporter_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportTestEndResponse.ProtoReflect.Descriptor instead.
func (*ReportTestEndResponse) Descriptor() ([]byte, []int) {
	return file_proto_reporter_proto_rawDescGZIP(), []int{5}
}

func (x *ReportTestEndResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type ReportSuiteEndRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SuiteRunId    string                 `protobuf:"bytes,1,opt,name=suite_run_id,json=suiteRunId,proto3" json:"suite_run_id,omitempty"`
	TimestampMs   int64                  `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportSuiteEndRequest) Reset() {
	*x = ReportSuiteEndRequest{}
	mi := &file_proto_reporter_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportSuiteEndRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportSuiteEndRequest) ProtoMessage() {}

func (x *ReportSuiteEndRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reporter_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportSuiteEndRequest.ProtoReflect.Descriptor instead.
func (*ReportSuiteEndRequest) Descriptor() ([]byte, []int) {
	return file_proto_reporter_proto_rawDescGZIP(), []int{6}
}

func (x *ReportSuiteEndRequest) GetSuiteRunId() string {
	if x != nil {
		return x.SuiteRunId
	}
	return ""
}

func (x *ReportSuiteEndRequest) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

type ReportSuiteEndResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportSuiteEndResponse) Reset() {
	*x = ReportSuiteEndResponse{}
	mi := &file_proto_reporter_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportSuiteEndResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportSuiteEndResponse) ProtoMessage() {}

func (x *ReportSuiteEndResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reporter_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportSuiteEndResponse.ProtoReflect.Descriptor instead.
func (*ReportSuiteEndResponse) Descriptor() ([]byte, []int) {
	return file_proto_reporter_proto_rawDescGZIP(), []int{7}
}

func (x *ReportSuiteEndResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UploadArtifactRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*UploadArtifactRequest_Metadata
	//	*UploadArtifactRequest_ChunkData
	Payload       isUploadArtifactRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadArtifactRequest) Reset() {
	*x = UploadArtifactRequest{}
	mi := &file_proto_reporter_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadArtifactRequest) ProtoMessage() {}

func (x *UploadArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reporter_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadArtifactRequest.ProtoReflect.Descriptor instead.
func (*UploadArtifactRequest) Descriptor() ([]byte, []int) {
	return file_proto_reporter_proto_rawDescGZIP(), []int{8}
}

func (x *UploadArtifactRequest) GetPayload() isUploadArtifactRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UploadArtifactRequest) GetMetadata() *ArtifactMetadata {
	if x != nil {
		if x, ok := x.Payload.(*UploadArtifactRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *UploadArtifactRequest) GetChunkData() []byte {
	if x != nil {
		if x, ok := x.Payload.(*UploadArtifactRequest_ChunkData); ok {
			return x.ChunkData
		}
	}
	return nil
}

type isUploadArtifactRequest_Payload interface {
	isUploadArtifactRequest_Payload()
}

type UploadArtifactRequest_Metadata struct {
	Metadata *ArtifactMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"`
}

type UploadArtifactRequest_ChunkData struct {
	ChunkData []byte `protobuf:"bytes,2,opt,name=chunk_data,json=chunkData,proto3,oneof"`
}

func (*UploadArtifactRequest_Metadata) isUploadArtifactRequest_Payload() {}

func (*UploadArtifactRequest_ChunkData) isUploadArtifactRequest_Payload() {}

type ArtifactMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TestRunId     string                 `protobuf:"bytes,1,opt,name=test_run_id,json=testRunId,proto3" json:"test_run_id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Type          ArtifactType           `protobuf:"varint,3,opt,name=type,proto3,enum=automation.v1.ArtifactType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactMetadata) Reset() {
	*x = ArtifactMetadata{}
	mi := &file_proto_reporter_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactMetadata) ProtoMessage() {}

func (x *ArtifactMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reporter_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactMetadata.ProtoReflect.Descriptor instead.
func (*ArtifactMetadata) Descriptor() ([]byte, []int) {
	return file_proto_reporter_proto_rawDescGZIP(), []int{9}
}

func (x *ArtifactMetadata) GetTestRunId() string {
	if x != nil {
		return x.TestRunId
	}
	return ""
}

func (x *ArtifactMetadata) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *ArtifactMetadata) GetType() ArtifactType {
	if x != nil {
		return x.Type
	}
	return ArtifactType_ARTIFACT_TYPE_UNSPECIFIED
}

type UploadArtifactResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ArtifactId    string                 `protobuf:"bytes,1,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadArtifactResponse) Reset() {
	*x = UploadArtifactResponse{}
	mi := &file_proto_reporter_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadArtifactResponse) ProtoMessage() {}

func (x *UploadArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_reporter_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadArtifactResponse.ProtoReflect.Descriptor instead.
func (*UploadArtifactResponse) Descriptor() ([]byte, []int) {
	return file_proto_reporter_proto_rawDescGZIP(), []int{10}
}

func (x *UploadArtifactResponse) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *UploadArtifactResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UploadArtifactResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_proto_reporter_proto protoreflect.FileDescriptor

const file_proto_reporter_proto_rawDesc = "" +
	"\n" +
	"\x14proto/reporter.proto\x12\rautomation.v1\"[\n" +
	"\x17ReportSuiteStartRequest\x12\x1d\n" +
	"\n" +
	"suite_name\x18\x01 \x01(\tR\tsuiteName\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\"<\n" +
	"\x18ReportSuiteStartResponse\x12 \n" +
	"\fsuite_run_id\x18\x01 \x01(\tR\n" +
	"suiteRunId\"z\n" +
	"\x16ReportTestStartRequest\x12 \n" +
	"\fsuite_run_id\x18\x01 \x01(\tR\n" +
	"suiteRunId\x12\x1b\n" +
	"\ttest_name\x18\x02 \x01(\tR\btestName\x12!\n" +
	"\ftimestamp_ms\x18\x03 \x01(\x03R\vtimestampMs\"9\n" +
	"\x17ReportTestStartResponse\x12\x1e\n" +
	"\vtest_run_id\x18\x01 \x01(\tR\ttestRunId\"\xd2\x01\n" +
	"\x14ReportTestEndRequest\x12\x1e\n" +
	"\vtest_run_id\x18\x01 \x01(\tR\ttestRunId\x121\n" +
	"\x06status\x18\x02 \x01(\x0e2\x19.automation.v1.TestStatusR\x06status\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12\x1f\n" +
	"\vstack_trace\x18\x04 \x01(\tR\n" +
	"stackTrace\x12!\n" +
	"\ftimestamp_ms\x18\x05 \x01(\x03R\vtimestampMs\"1\n" +
	"\x15ReportTestEndResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\\\n" +
	"\x15ReportSuiteEndRequest\x12 \n" +
	"\fsuite_run_id\x18\x01 \x01(\tR\n" +
	"suiteRunId\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x03R\vtimestampMs\"2\n" +
	"\x16ReportSuiteEndResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x82\x01\n" +
	"\x15UploadArtifactRequest\x12=\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1f.automation.v1.ArtifactMetadataH\x00R\bmetadata\x12\x1f\n" +
	"\n" +
	"chunk_data\x18\x02 \x01(\fH\x00R\tchunkDataB\t\n" +
	"\apayload\"\x7f\n" +
	"\x10ArtifactMetadata\x12\x1e\n" +
	"\vtest_run_id\x18\x01 \x01(\tR\ttestRunId\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12/\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1b.automation.v1.ArtifactTypeR\x04type\"x\n" +
	"\x16UploadArtifactResponse\x12\x1f\n" +
	"\vartifact_id\x18\x01 \x01(\tR\n" +
	"artifactId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage*r\n" +
	"\n" +
	"TestStatus\x12\x1b\n" +
	"\x17TEST_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12TEST_STATUS_PASSED\x10\x01\x12\x16\n" +
	"\x12TEST_STATUS_FAILED\x10\x02\x12\x17\n" +
	"\x13TEST_STATUS_SKIPPED\x10\x03*\x94\x01\n" +
	"\fArtifactType\x12\x1d\n" +
	"\x19ARTIFACT_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18ARTIFACT_TYPE_SCREENSHOT\x10\x01\x12\x17\n" +
	"\x13ARTIFACT_TYPE_VIDEO\x10\x02\x12\x15\n" +
	"\x11ARTIFACT_TYPE_LOG\x10\x03\x12\x17\n" +
	"\x13ARTIFACT_TYPE_TRACE\x10\x042\xf8\x03\n" +
	"\x0fReporterService\x12c\n" +
	"\x10ReportSuiteStart\x12&.automation.v1.ReportSuiteStartRequest\x1a'.automation.v1.ReportSuiteStartResponse\x12`\n" +
	"\x0fReportTestStart\x12%.automation.v1.ReportTestStartRequest\x1a&.automation.v1.ReportTestStartResponse\x12Z\n" +
	"\rReportTestEnd\x12#.automation.v1.ReportTestEndRequest\x1a$.automation.v1.ReportTestEndResponse\x12]\n" +
	"\x0eReportSuiteEnd\x12$.automation.v1.ReportSuiteEndRequest\x1a%.automation.v1.ReportSuiteEndResponse\x12c\n" +
	"\x12UploadTestArtifact\x12$.automation.v1.UploadArtifactRequest\x1a%.automation.v1.UploadArtifactResponse(\x01B*Z(github.com/ranjith035/morego/proto/v1;v1b\x06proto3"

var (
	file_proto_reporter_proto_rawDescOnce sync.Once
	file_proto_reporter_proto_rawDescData []byte
)

func file_proto_reporter_proto_rawDescGZIP() []byte {
	file_proto_reporter_proto_rawDescOnce.Do(func() {
		file_proto_reporter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_reporter_proto_rawDesc), len(file_proto_reporter_proto_rawDesc)))
	})
	return file_proto_reporter_proto_rawDescData
}

var file_proto_reporter_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_reporter_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_reporter_proto_goTypes = []any{
	(TestStatus)(0),                  // 0: automation.v1.TestStatus
	(ArtifactType)(0),                // 1: automation.v1.ArtifactType
	(*ReportSuiteStartRequest)(nil),  // 2: automation.v1.ReportSuiteStartRequest
	(*ReportSuiteStartResponse)(nil), // 3: automation.v1.ReportSuiteStartResponse
	(*ReportTestStartRequest)(nil),   // 4: automation.v1.ReportTestStartRequest
	(*ReportTestStartResponse)(nil),  // 5: automation.v1.ReportTestStartResponse
	(*ReportTestEndRequest)(nil),     // 6: automation.v1.ReportTestEndRequest
	(*ReportTestEndResponse)(nil),    // 7: automation.v1.ReportTestEndResponse
	(*ReportSuiteEndRequest)(nil),    // 8: automation.v1.ReportSuiteEndRequest
	(*ReportSuiteEndResponse)(nil),   // 9: automation.v1.ReportSuiteEndResponse
	(*UploadArtifactRequest)(nil),    // 10: automation.v1.UploadArtifactRequest
	(*ArtifactMetadata)(nil),         // 11: automation.v1.ArtifactMetadata
	(*UploadArtifactResponse)(nil),   // 12: automation.v1.UploadArtifactResponse
}
var file_proto_reporter_proto_depIdxs = []int32{
	0,  // 0: automation.v1.ReportTestEndRequest.status:type_name -> automation.v1.TestStatus
	11, // 1: automation.v1.UploadArtifactRequest.metadata:type_name -> automation.v1.ArtifactMetadata
	1,  // 2: automation.v1.ArtifactMetadata.type:type_name -> automation.v1.ArtifactType
	2,  // 3: automation.v1.ReporterService.ReportSuiteStart:input_type -> automation.v1.ReportSuiteStartRequest
	4,  // 4: automation.v1.ReporterService.ReportTestStart:input_type -> automation.v1.ReportTestStartRequest
	6,  // 5: automation.v1.ReporterService.ReportTestEnd:input_type -> automation.v1.ReportTestEndRequest
	8,  // 6: automation.v1.ReporterService.ReportSuiteEnd:input_type -> automation.v1.ReportSuiteEndRequest
	10, // 7: automation.v1.ReporterService.UploadTestArtifact:input_type -> automation.v1.UploadArtifactRequest
	3,  // 8: automation.v1.ReporterService.ReportSuiteStart:output_type -> automation.v1.ReportSuiteStartResponse
	5,  // 9: automation.v1.ReporterService.ReportTestStart:output_type -> automation.v1.ReportTestStartResponse
	7,  // 10: automation.v1.ReporterService.ReportTestEnd:output_type -> automation.v1.ReportTestEndResponse
	9,  // 11: automation.v1.ReporterService.ReportSuiteEnd:output_type -> automation.v1.ReportSuiteEndResponse
	12, // 12: automation.v1.ReporterService.UploadTestArtifact:output_type -> automation.v1.UploadArtifactResponse
	8,  // [8:13] is the sub-list for method output_type
	3,  // [3:8] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_reporter_proto_init() }
func file_proto_reporter_proto_init() {
	if File_proto_reporter_proto != nil {
		return
	}
	file_proto_reporter_proto_msgTypes[8].OneofWrappers = []any{
		(*UploadArtifactRequest_Metadata)(nil),
		(*UploadArtifactRequest_ChunkData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_reporter_proto_rawDesc), len(file_proto_reporter_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_reporter_proto_goTypes,
		DependencyIndexes: file_proto_reporter_proto_depIdxs,
		EnumInfos:         file_proto_reporter_proto_enumTypes,
		MessageInfos:      file_proto_reporter_proto_msgTypes,
	}.Build()
	File_proto_reporter_proto = out.File
	file_proto_reporter_proto_goTypes = nil
	file_proto_reporter_proto_depIdxs = nil
}
